### ISSUE TITLE
Update code for Blazor's new IJSInterop abstraction

### ISSUE THREAD

**Issue by DNF-SaS** [Tewr/BlazorFileReader#1]
Blazor.registerFunction() is no longer needed, because the new IJSRuntime.InvokeAsync() invokes the (specified) method on the current window-object.

**Comment by Tewr** [comment]
The only `async` method I have is [unmarshalled](https://github.com/Tewr/BlazorFileReader/blob/b749b5ddf8ee40c8d621012a5ca60fb29946c557/src/FileReaderComponent/FileReaderJsInterop.cs#L59). Looks like `RegisteredFunction` will be phased out anyway in 0.5.0 (it's no longer in the repo?), so the interop has to be changed for sure. Can't really see at the current state of affairs how Unmarshalled calls should be done. Looks like [MonoWebAssemblyJSRuntime](https://github.com/aspnet/Blazor/blob/dbef0ddee5e5a2152212276565c044829e8d36a6/src/Mono.WebAssembly.Interop/MonoWebAssemblyJSRuntime.cs) exposes the method, but ill have to migrate first to see if this is viable, might be something I'm missing when just reading source. Perhaps I'll suggest `IJSRuntime.InvokeUnmarshalledAsync()`, to the Blazor team, unless its already in the pipeline, or if there is another way to do it.

**Comment by DNF-SaS** [comment]
I've extended the FileReaderJsInterop by two functions for mocking the old functionality of JSInterop. 
It's oviously working on MonoRuntime only, but I would suggest that this is okay for the moment.
```
private static T InvokeOnMono<T>(string identifier, params object[] args)
{
    if ( JSRuntime.Current is MonoWebAssemblyJSRuntime mono )
    {
	    return mono.Invoke<T>(identifier, args);
    }

    throw new NotImplementedException($"TODO: Support {identifier} on other runtimes.");
}

private static TRes InvokeUnmarshalledOnMono<T0, T1, TRes>(string identifier, T0 arg0, T1 arg1)
{
    if ( JSRuntime.Current is MonoWebAssemblyJSRuntime mono )
    {
	    return mono.InvokeUnmarshalled<T0, T1, TRes>(identifier, arg0, arg1);
    }

    throw new NotImplementedException($"TODO: Support {identifier} on other runtimes.");
}
```
Additionally, the TypeScript-Code should be adapted so that the code from Blazor.registerFunction() is moved to some function residing below window.(namespace).

**Comment by Tewr** [comment]
Yes, I did something like this yesterday, think its the way to go for this. I'll have to pass all sync methods to async as well, to avoid using the special methods, and implement the js/ts as a class instance.
As you are showing a bit of interest, I [pushed ](https://github.com/Tewr/BlazorFileReader/tree/0.5.0-p1) a half-built branch which depends on 0.5.0

**Comment by DNF-SaS** [comment]
Pulled the 0.5-Branch; it's pretty work in progress, so I'll wait in order to prevent merge conflicts.

**Comment by Tewr** [comment]
I've got it fully working now. Had to change most of the API but in any case I like it better now. There is some weird behaviour when calling back to .NET from js, I was unable to figure out what it was. I didn't manage to call back without more than one parameter (first one was lost, not the second one?). Might be a bug in blazor, might have been me doing something goofy. In any case, current solution is not that bad anyway, might even be better.

**Comment by DNF-SaS** [comment]
Great!
You copied your changes from 0.5.0-p1 back to the master-branch? (no merge?)

**Comment by Tewr** [comment]
:) Well, the intention was a merge, but didnt really end up that way, had some conflict gore when branching out in the middle to save 0.4.0. That'll teach me not to merge late at night

**Comment by DNF-SaS** [comment]
I suppose, every dev has some bad memories about git and merging...  ;-)
