### ISSUE TITLE
Click to add during drag drop

### ISSUE THREAD

**Issue by OliverVisual** [Tewr/BlazorFileReader#101]
**Describe the bug**
This is a feature suggestion. Would be great to be able to click the drop target and open a file dialog allowing the user to select a file. Otherwise the drag drop feature doesn't hold up on a mobile device.

**Comment by Tewr** [comment]
Hello Olivier, thank you for your suggestion. 
I'm pretty sure this is already possible, but, alas, I lack an example in the demo project. You could have a hidden input in the drop target.

However as it is now, I don't think the input itself can be a drop target. That would require a change of the current javascript. I'll look into it.

**Comment by OliverVisual** [comment]
Hi,

I tried to do this and opening the file dialogue works, but I could find a way to add the file into the drop target?

We don’t want to display a button aswell as a droptarget.

**Comment by Tewr** [comment]
Yea so I remember it as you could set your dropzone div to relative
positioning. Then the input inside the dropzone div with absolute
positioning and opacity 0 and width height 100%.

Is this what you tried to do?

**Comment by OliverVisual** [comment]
I called the input using JS to open the dialog and tried to get the file and pass it into the drop zone.

I’m trying to get the file to appear in the drop zone.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tewr** [comment]
I added an example of clickable drag n drop in the demo project. The example is using the native drop of the input element.
