### ISSUE TITLE
how i can interrupt read file ?

### ISSUE THREAD

**Issue by codesoroush** [Tewr/BlazorFileReader#102]
its not a bug , but i dont know how i can interrupt a proccess

**Comment by codesoroush** [comment]
Right now I'm using this method, I don't know if it's standard


```
  if (cancelMethod)
         {
               cancelMethod = false;
               Output = "upload canceled";
               await ClearFile();
               value = 0;
               stopwatch.Stop();
                StateHasChanged();
                 return;
          }
```

**Comment by Tewr** [comment]
This depends on how you read the stream.

If you are using one of the examples when the stream is read in chunks using a while loop: let the cancel button set a Boolean to true. I the while loop, check if the Boolean is set to true, if that is the case bail out of the while loop and then do some cleanup.

If you are using stream.copytoasync to read the stream, you could pass a cancelationtoken to that method and your cancelbutton would cancel the token. Then the copytoasync method will bail out of it's internal while loop.

**Comment by Tewr** [comment]
I'm closing this as there is no feedback from you. I might create an example in the future, it would look something like the code you posted inside the read loop I guess...
