### ISSUE TITLE
does not work in Edge

### ISSUE THREAD

**Issue by liuliang-wt** [Tewr/BlazorFileReader#106]
the download works in chrome, but not edge. Seems that link.click() has no effect in Edge

**Comment by Tewr** [comment]
Initializer is failing with nullref

**Comment by Tewr** [comment]
This is related to publishing and is not reproducible in normal builds... and I'm not sure with "normal" publishing either....

**Comment by Tewr** [comment]
@liuliang-wt you are talking about the live demo right? cause IMO the live demo is the only thing that is actually broken. I think they added a trailing / afeter the publish directory in the latest release and I didnt notice, so it botched the publish

**Comment by Tewr** [comment]
Republished, edge is ok
