### ISSUE TITLE
not able to add a using directive for Blazor.FileReader

### ISSUE THREAD

**Issue by nk111** [Tewr/BlazorFileReader#107]
**Describe the bug**
I'm not able to add a using directive for Blazor.FileReader. It seems like there is some namespace pollution due to naming conflicts? I wonder if the namespace for the FileReader should be Tewr.Blazor.FileReader to avoid this?

**To Reproduce**
1.  created the solution/project structure like in the screenshot below
2.  added the nuget package Tewr.Blazor.FileReader
3.  try to add @using Blazor.FileReader to _Imports.razor

**Expected behavior**
The namespace Blazor.FileReader should be imported

**Screenshots**
![image](https://user-images.githubusercontent.com/155322/73915789-5c6e3780-48bc-11ea-9f7c-85351871a695.png)

**Project type**
**'Client-side'/'CSB'**

**Environment**
 - Browser chrome
 - Version of Blazor.FileReader 1.3.0.20033
 - Version of .net sdk AspNetCore.Blazor 3.2.0-Preview1.20073.1
 
**Additional context**

**Comment by Tewr** [comment]
I think renaming this library is a bit harsh at this point.

As the error states, the conflict is with how you named your own project, it's not a conflict with any other library, or with Blazor itself.

Did you try the classic .net approach to avoid namespace conflicts? I must say I didn't try this in Blazor / razor but it's pretty fundamental so it should most likely work.

https://stackoverflow.com/questions/5681537/namespace-conflict-in-c-sharp

**Comment by Tewr** [comment]
For reference, if anyone runs in to this problem (You could if you named your project xxx.yyy.Blazor), then instead of `@using Blazor.FileReader`, use `@using global::Blazor.FileReader`

**Comment by nk111** [comment]
Thanks for the heads up @Tewr ! The global:: approach did solve the problem indeed.
