### ISSUE TITLE
FileReaderParams error

### ISSUE THREAD

**Issue by CD1010** [Tewr/BlazorFileReader#108]
I get this error when i tried to update to latest version 1.3.0.20033
Works fine for version 1.2.0.19363
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Unable to load one or more of the requested types.
Could not load type 'Blazor.FileReader.ReadFileParams' from assembly 'Blazor.FileReader, Version=1.2.0.19363, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 4 that is incorrectly aligned or overlapped by a non-object field.

**To Reproduce**
start app.  Blazor page injects FileReader object

**Expected behavior**
Application should start. It gets above exception in startup.cs

**Project type**
ASP.net Core Blazor app
**Environment**
Asp.net core 3.1 on win 10.  VS 2019 latest version.

**Comment by Tewr** [comment]
This looks complicated. The manual tests as well as integration tests are passing where as this sounds like basic usage. I need more info to reproduce this. Could you maybe create a new project that reproduces your problem and post it in a repo?

That said, you have revealed that the 1.3.0.20033 package contains the wrong assembly version, but I don't think it's relevant

**Comment by Turbo-Thorschten** [comment]
I experienced the same error in use with reflection. The offsets seem to be incorrect. You can reproduce the bug by calling GetTypes() on the Assembly.

**Comment by Tewr** [comment]
Thanks for the repro.
