### ISSUE TITLE
UseWasmSharedBuffer=true not supported when updated to Blazor WASM 3.2.0 Preview 3

### ISSUE THREAD

**Issue by szmalec** [Tewr/BlazorFileReader#121]
I use [BlazorFileReader v1.4.0.20072](https://github.com/Tewr/BlazorFileReader/tree/v1.4.0.20072) in Blazor WASM (CSB) app:
```C#
builder.Services.AddFileReaderService(options => options.UseWasmSharedBuffer = true);
```
After update to [Blazor WebAssembly 3.2.0 Preview 3](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/) new [exception](https://github.com/Tewr/BlazorFileReader/blob/v1.4.0.20072/src/Blazor.FileReader/SetupExtension.cs#L41) started to occur: `UseWasmSharedBuffer=true is not supported on this platform.`
Setting `UseWasmSharedBuffer` to `false` resolved problem.

Is it related to this changes: [1](https://github.com/dotnet/aspnetcore/commit/7ba8d0671768d66a3c979fb509b1c52d7e480b50#diff-514554bd1120b4f06b0ba9fee70c3792L16), [2](https://github.com/dotnet/aspnetcore/commit/7ba8d0671768d66a3c979fb509b1c52d7e480b50#diff-1c85ba08b63bdc4f1bea3b09a57b25edR9), [3](https://github.com/dotnet/aspnetcore/commit/a0c76e5a4ca78efd26ec19694034b2529cbf11db#diff-514554bd1120b4f06b0ba9fee70c3792R8) and [4](https://github.com/dotnet/aspnetcore/commit/47536a3c14943b07cab386c27f0769d54cc2a227)?

**Comment by Tewr** [comment]
They have been renaming dlls, namespaces and classes each release this year. Same problem as #119 probably, just a different rename. Gotta upgrade and debug to see what happened.

**Comment by Tewr** [comment]
At first glance, looks like the method I'm using is no longer in the class, it has become an extension method, looking at [this](https://github.com/dotnet/aspnetcore/commit/cb293661e118f66c798e9a5d9315408e871fce3d)

**Comment by Tewr** [comment]
Indeed, using the most explicit method instead works, this will be the fix. I will publish this soon

**Comment by szmalec** [comment]
Thank you for the patch.
I have only one more question - was an upgrade to [5.0.0-preview.1.20124.5](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-1/) needed [here](https://github.com/Tewr/BlazorFileReader/pull/122/files#diff-d3ad9c6728c6c80040bace4d36fc99c0L11)? [Blazor WebAssembly 3.2.0 Preview 3 release page](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/) says nothing about that...

**Comment by Tewr** [comment]
> was an upgrade to 5.0.0-preview.1.20124.5 needed here

I had downgrade warnings for the server-side version, so I did a blanket update for all deps to the latest version. That might have been overkill or a misreading of the errors on my part... As now when you ask the question I have some doubts.

Did you run into any particular problem due to this?

**Comment by szmalec** [comment]
I didn't run into any particular problems because I stopped the update when I saw a message saying that the following packages would be upgraded:
`
Microsoft.AspNetCore.Authorization.3.1.2 -> Microsoft.AspNetCore.Authorization.5.0.0-preview.1.20124.5
Microsoft.AspNetCore.Components.3.1.2 -> Microsoft.AspNetCore.Components.5.0.0-preview.1.20124.5
Microsoft.AspNetCore.Components.Analyzers.3.1.2 -> Microsoft.AspNetCore.Components.Analyzers.5.0.0-preview.1.20124.5
Microsoft.AspNetCore.Metadata.3.1.2 -> Microsoft.AspNetCore.Metadata.5.0.0-preview.1.20124.5
Microsoft.Extensions.DependencyInjection.Abstractions.3.1.2 -> Microsoft.Extensions.DependencyInjection.Abstractions.5.0.0-preview.1.20120.4
Microsoft.Extensions.Logging.Abstractions.3.1.2 -> Microsoft.Extensions.Logging.Abstractions.5.0.0-preview.1.20120.4
Microsoft.Extensions.Options.3.1.2 -> Microsoft.Extensions.Options.5.0.0-preview.1.20120.4
Microsoft.Extensions.Primitives.3.1.2 -> Microsoft.Extensions.Primitives.5.0.0-preview.1.20120.4
Microsoft.JSInterop.3.1.2 -> Microsoft.JSInterop.5.0.0-preview.1.20120.4
System.ComponentModel.Annotations.4.7.0 -> System.ComponentModel.Annotations.5.0.0-preview.1.20120.5
System.Runtime.CompilerServices.Unsafe.4.7.0 -> System.Runtime.CompilerServices.Unsafe.5.0.0-preview.1.20120.5
System.Text.Encodings.Web.4.7.0 -> System.Text.Encodings.Web.5.0.0-preview.1.20120.5
System.Text.Json.4.7.1 -> System.Text.Json.5.0.0-preview.1.20120.5
Tewr.Blazor.FileReader.1.3.0.20049 -> Tewr.Blazor.FileReader.1.5.0.20092
`

Maybe a change from version 3.1.* to 5.0.0-preview.1.20120.4 would not cause problems but on the other hand I thought why take a risk, especially that on "Blazor WebAssembly 3.2.0 Preview 3 release" web page there is nothing about v5.0.0-preview.1.20120.4 and on "ASP.NET Core updates in .NET 5 Preview 1" web page there is something about "breaking changes" ;)
I also have in mind that with every new "preview" version (eg. of Blazor WASM) I encounter some new problems ;) - so I assumed that a rather unnecessary change of versions of other packages may also not be recommended.

I also had downgrade warnings in VS but I have tried to manualy replace "5.0.0-preview.1.20120.4" to "3.1.3" in *.csproj files - after that Blazor.FileReader compiles without any problem...

**Comment by Tewr** [comment]
Well. Im going to have a look into what I actually need, maybe I can reduce the graph even further, because I didn't change deps since the beginning of the blazor project, didn't really Dawn on me before. I'll look into it.

**Comment by Tewr** [comment]
I decided to downgrade for now. I Must say that the current versioning strategy is confusing ( 3.1.3 vs 5.0.0p1?)

Basically, this library is using only two types that are very simle: `ElementRef` (a glorified integer) and  `IJSRuntime`. There are some indirect references to the underlying implementation of IJSRuntime (the reason for this bug in the first place) but as the references are indirect, the package reference graph has no impact whatsoever.
