### ISSUE TITLE
Error logging in case HTMLElement is null

### ISSUE THREAD

**Issue by catlan** [Tewr/BlazorFileReader#127]
**Describe the bug**
I just spend more time than I'm willing to admit in public, debugging an issue which I think is easy to make and would like to suggest adding some error logging.

**To Reproduce**
1. Page with `<input />`
2. User selects a file
3. Display a loading indicator

My mistake was that the loading indicator did replace the` <input />`. 

The `IFileReaderRef` remains valid, but `EnumerateFilesAsync` will be empty because [GetFileCount](https://github.com/Tewr/BlazorFileReader/blob/master/src/Blazor.FileReader/script/FileReaderComponent.ts#L97) has no longer a `HTMLElement` do work with.

My suggestion is to add
```
    private LogIfMissing(element: HTMLElement) {
        if (element == null) {
            console.log("BlazorFileReader HTMLElement is null. Can't access IFileReaderRef after HTMLElement was removed from DOM.");
        }
    }
```
for the following calls: [RegisterDropEvents](https://github.com/Tewr/BlazorFileReader/blob/73d50f197dfbe15bc90344748bbbb7541df9d3c6/src/Blazor.FileReader/script/FileReaderComponent.ts#L49), [UnregisterDropEvents](https://github.com/Tewr/BlazorFileReader/blob/73d50f197dfbe15bc90344748bbbb7541df9d3c6/src/Blazor.FileReader/script/FileReaderComponent.ts#L73), [GetFileCount](https://github.com/Tewr/BlazorFileReader/blob/73d50f197dfbe15bc90344748bbbb7541df9d3c6/src/Blazor.FileReader/script/FileReaderComponent.ts#L97), [ClearValue](https://github.com/Tewr/BlazorFileReader/blob/73d50f197dfbe15bc90344748bbbb7541df9d3c6/src/Blazor.FileReader/script/FileReaderComponent.ts#L106), [GetFileInfoFromElement](https://github.com/Tewr/BlazorFileReader/blob/73d50f197dfbe15bc90344748bbbb7541df9d3c6/src/Blazor.FileReader/script/FileReaderComponent.ts#L116), [OpenRead](https://github.com/Tewr/BlazorFileReader/blob/73d50f197dfbe15bc90344748bbbb7541df9d3c6/src/Blazor.FileReader/script/FileReaderComponent.ts#L145).

**Project type**
**'Client-side'/'CSB'**

**Environment**
 - Chrome Version 81.0.4044.113
 - Version of Blazor.FileReader: 1.5.0.20109
 - Version of .net sdk:3.1.201

**Comment by Tewr** [comment]
I approve of this. I think in general that the API is pretty stable so its a good time for this type of features.
