### ISSUE TITLE
Blazor 0.8.0 breaks FileReader

### ISSUE THREAD

**Issue by nickbeau** [Tewr/BlazorFileReader#13]
Hi All

Should be a simple referencing fix, but Blazor 0.8.0 has moved the ElementRef to Microsoft.AspNetCore.Components from Microsoft.AspNetCore.Blazor

**Comment by Tewr** [comment]
Thank you for the heads up! I had a quick look at lunch and the first attempt to upgrade the project failed miserably, so I'll go ahead and classify this as a "tricky" referencing fix instead... 😄

**Comment by IvanJosipovic** [comment]
I have the core project fixed in my repo, see commit here https://github.com/IvanJosipovic/BlazorFileReader/commit/05ba8001cc8bb19384f105722f20f82c74faf2de

i have not fixed the Demo projects

**Comment by Tewr** [comment]
Thank you, I made a working build yesterday (Tewr@6385c15de69e0b27a4e4a8da3db90846ab0e5425) but I have runtime issues: `Could not find type "MonoWebAssemblyJSRuntime" in namespace "Mono.WebAssembly.Interop" in assembly "Mono.WebAssembly.Interop"`. I'm not sure what's missing, but smells like the linker has been removing too much. Which is weird, cause I'm pretty sure I managed to disable it (using `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>`). Last time I hit the wall (0.6.0?) I managed to recreate all projects from scratch and that kind of sorted out stuff. I might try that this time around, too, I'm halfway there, I think. I hope I'm not right but maybe referencing `MonoWebAssemblyJSRuntime` is no longer a viable option, i'd have to fall back to the marshalled version of interop.

@IvanJosipovic : did you manage to get this running under WebAssembly in any other project?

**Comment by Tewr** [comment]
Ok so I've managed to get this working, but it looks like I will have rearchitecture this a bit: the component can no longer reference `MonoWebAssemblyJSRuntime` directly. It makes sense for components which are x-plat not to know about platform specific classes, and apparently 0.8.0 this is business: no co-habitation of these dependencies is possible. I'll just have to wrap it up in an interface and the caller WebAssembly project has to provide it, and all should be fine.

**Comment by nickbeau** [comment]
Thanks everyone. We really appreciate your work :)

**Comment by Tewr** [comment]
I have pushed a working version to branch. Ill just have to test server-side blazor before pushing the package to nuget.

In the meantime, the working source, and some new setup instructions for WASM are [here](/Tewr/BlazorFileReader/tree/release/0.8.0-preview).

Setup is a bit messy for now, I'll have to think about how to make it prettier. I benchmarked about 30% slower on WASM without unmarshalled calls, so I've decided to keep it. Now I'll just have to find a more user-friendly way of setting it up...

**Comment by Tewr** [comment]
I've published a [prerelease version](https://www.nuget.org/packages/Tewr.Blazor.FileReader/0.8.0-preview-120219) on nuget. I'ts working well with Wasm, but I still haven't figured out server-side blazor. I'm going to open an issue at the asp.net repo and see if they can help me out. I pused a minimal repro project to [Tewr/blazor0.8.0p1bugrepro](/Tewr/blazor0.8.0p1bugrepro) if someone is interested in helping me investigating. I have a feeling that it might just be my setup which is broken...

**Comment by Tewr** [comment]
Turns out that someone already posted the bug. So at least I'm not crazy. Apparently static content serving from blazorlib is a feature that no longer exists - "a known limitation with the Razor Components template in Preview 2" . [This bug](/aspnet/AspNetCore/issues/7300) is what I'm experiencing, and like it says it's being tracked in issue aspnet/AspNetCore/issues/6349

**Comment by springy76** [comment]
~~Is there a quick workaround for this problem (copying and referencing the .js file by hand) or will it not work all the way with server side razor components?~~

I just took/copied FileReaderComponent.js from 0.8 branch into wwwroot of server project and referenced it in index.html **after** `<script src="_framework/components.server.js"></script>` -- seems to work properly (once I had a memory access problem in MessagePack decode of SignalR on upload but it neither was repeatable nor trackable to a specific source).

**Comment by Tewr** [comment]
@springy76 thank you for your idea and comments. I ~~might~~ put this in the readme for 0.8.0. 

Your solution could possibly be automated using a powershell script in the nuget package, but I'll wait and see a bit what the blazor team comes up with, probably not worth the investment at the moment (I'm not sure about how I could distingush WASM from server-side at nuget-time, as there is no WASM platform target..)

**Comment by Tewr** [comment]
well this is ancient history now, remaining issues tracked in #18 and #19
