### ISSUE TITLE
Are you sure that the code is executed on the client?

### ISSUE THREAD

**Issue by wangjunjx8868** [Tewr/BlazorFileReader#130]
` public async Task ReadFile()
    {
        foreach (var file in await fileReaderService.CreateReference(inputTypeFileElement).EnumerateFilesAsync())
        {
            // Read into buffer and act (uses less memory)
            await using (Stream stream = await file.OpenReadAsync()) {
                // Do (async) stuff with stream...
                await stream.ReadAsync(buffer, ...);
                // The following will fail. Only async read is allowed.
                stream.Read(buffer, ...)
            }

            // Read into memory and act
            using (MemoryStream memoryStream = await file.CreateMemoryStreamAsync(4096)) {
                // Sync calls are ok once file is in memory
                memoryStream.Read(buffer, ...)
            }
        }
    }`

Are you sure that the code is executed on the client? How to understand the data transmission to the server?

**Comment by Tewr** [comment]
Hello,

The answer to your two questions is "That depends". But I don't think you are in the right place - both of your questions are general questions about how the Blazor Framework works.

Please read [this](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1) article first and make sure you understand what you are trying to do.

That said, let me answer the questions regarding the Blazor framework in short:

- If you are using "Blazor WebAssembly", everything is executed on the client. Nothing is transmitted to a server unless you explicitly connect to a server using `HttpClient`.

- If you are using "Blazor Server", all C# is executed on the server, but most calls in the API will result in a round-trip to the client and execute some client code. `await file.OpenReadAsync()` will register a js filereader, `await stream.ReadAsync(buffer, ...);` will read a chunk using the said reader and return the data to the server `buffer`. etcetera.

**Comment by Tewr** [comment]
I'm closing this, feel free to reopen if my answer wasn't clear.
