### ISSUE TITLE
Demo site load time?

### ISSUE THREAD

**Issue by arivera12** [Tewr/BlazorFileReader#133]

**Comment by Tewr** [comment]
Hello.

Could you be a bit more specific?

**Comment by arivera12** [comment]
The demo site takes about 2-3 minutes to load when you navigate to it.

Do you understand now?

**Comment by Tewr** [comment]
Might be possible to configure the linker to make it work. It hasn't worked in the past, broke the excel demo and the reflection demo, but I can give it a shot.

**Comment by arivera12** [comment]
Don't worry site stills loads this issue has low priority.

**Comment by Tewr** [comment]
It's slightly faster now. In any case I'm not going to work more on load speed atm
