### ISSUE TITLE
Can you move your library to your own namespace?

### ISSUE THREAD

**Issue by arivera12** [Tewr/BlazorFileReader#134]
Blazor namespace conflicts with many libraries that have nested Blazor as a namespace. 

Example MyLib.Blazor conflicts with you library. 

Your library should have a parent namespace like `Tewr.Blazor` or `BlazorFileReader` to prevent namespace collision.

I ended doing this cause is looking Blazor on my library instead of yours.

`global::Blazor.FileReader.IFileReaderRef`

**Comment by Tewr** [comment]
Discussed in #107 .
Its doesnt seem like a widespread problem, I'll take this as a second vote. I'm taking it  into consideration, probably merits a line of documentation. Weighing it against breaking the build of all other package consumers.

**Comment by arivera12** [comment]
Your library works on c# regular class file but doesn't work on blazor context take a look of this screenshot.

![image](https://user-images.githubusercontent.com/5600102/83335061-3e1bb580-a278-11ea-8168-f8d712c81013.png)

Form some reason it's confusing OneLine.Blazor with your namespace.

I know this is a breaking change on your library.

But you will still receive this issue again and again until you move it into a personal/company namespace.

I suggest you move your library into `Tewr.Blazor` or `BlazorFileReader` to prevent namespace collision.

**Comment by arivera12** [comment]
I tried inherit from a regular c# file into blazor context and still doesn't work.

**Comment by Tewr** [comment]
Did you try `@using global::Blazor.FileReader`?

**Comment by arivera12** [comment]
> Did you try `@using global::Blazor.FileReader`?

I tried it but doesn't work, visual studio still confuses the namespace. 

I workaround it returning another datatype compatible with your file reader model and with extra work done under the hood .

PS. You should still consider moving you library to a personal/company namespace.

**Comment by arivera12** [comment]
This one solid reason for moving you library to a personal/company namespace:

The global:: qualification isn't supported.

Importing components with aliased using statements (for example, @using Foo = Bar) isn't supported.

[Blazor Components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#import-components)

**Comment by Tewr** [comment]
Convinced.
