### ISSUE TITLE
Additive file input example?

### ISSUE THREAD

**Issue by arivera12** [Tewr/BlazorFileReader#135]
How can I make file input additive? I tried demo with 
```
DropReference = FileReaderService.CreateReference(DropTargetInput);
await DropReference.RegisterDropEventsAsync(IsMultiple);
```
But file input doesn't get additive.

I need to drag all files into a single action to add all of them together.

**Comment by Tewr** [comment]
The demo uses an element as a drop target, not an input. If you use an input as a drop target, it uses the native input as storage for the files if I remember correctly. I'm not sure additive AND clickable drop target is supported as it is now. It's not in the demo. Doesn't mean it's not possible though.

**Comment by arivera12** [comment]
> I'm not sure additive AND clickable drop target is supported as it is now. 

This is exactly what I am looking for.

**Comment by arivera12** [comment]
It seems is not supported I tried mixing both drop target and file input and dragging new files replaces the first one once you loaded one using file input click event.

**Comment by Tewr** [comment]
I managed to make it work using one reader for drop on the wrapper element, and one for the clicks. Its not very pretty, native support would be better. But it's workable with the current version at least.

**Comment by Tewr** [comment]
https://github.com/Tewr/BlazorFileReader/blob/AdditiveAndClickableDragNDrop/src/Demo/Blazor.FileReader.Demo.Common/DragnDropCommon.razor

**Comment by arivera12** [comment]
I added a button below the drop zone to bypass this issue. but I still needed both readers and manage the collections properly.

**Comment by Tewr** [comment]
it's only available in the branch in the comment above. 

I think it's a feature worth pursuing, but I don't immediately see how I can do it without using two elements... but I might be a bit home blind,  the current code is very focused on using a single element.

**Comment by arivera12** [comment]
I manage it using both readers and manage the readers into a single collection and seems to be working properly.

**Comment by arivera12** [comment]
You can add a <input type="file"> hidden and add a onclick event on the dropzone which triggers the input file then internally join both readers into a single collection.

**Comment by Tewr** [comment]
Yea well that's basically what I did right? Or do you mean the library should actually add a hidden wrapper element? I think that adds a lot of complexity not only for the code but also for customizing the dom. I want to leave the dom out of it. My philosophy is to mess with the dom as little as possible and let the library consumers decide what elements to put where.

On the other hand, the example I did above with two readers and drop and drag events all over the place is quite complex as well. There is probably a way to simplify it...

**Comment by arivera12** [comment]
> Yea well that's basically what I did right? Or do you mean the library should actually add a hidden wrapper element? I think that adds a lot of complexity not only for the code but also for customizing the dom. I want to leave the dom out of it. My philosophy is to mess with the dom as little as possible and let the library consumers decide what elements to put where.
> 
> On the other hand, the example I did above with two readers and drop and drag events all over the place is quite complex as well. There is probably a way to simplify it...

My suggestion its just a workaround it should as simple of adding additive option to the input file. But not sure how you gonna make this to work cause every time you open a device file system to pick a file it replaces the before picked files. So you need to manage the collection your self to bypass the current behavior.

**Comment by Tewr** [comment]
Finally, it came to me in a dream that a javascript `File` reference is valid throughout a session. So the secret is to store it whenever it's available using the change event. The `OpenReadAsync `call creates a Stream that tracks the file reference, this is what the example uses.

One could argue I should maybe track it earlier up the chain, before creating the stream, but then `FileReference `would have to implement `IDisposable`. I tried it out and consuming code didn't look very... .net. And disposals where everywhere. HIgh leak risk. Most people knows that a `Stream` should be disposed. A FileReference, not so much... so I'm keeping the current api.

**Comment by arivera12** [comment]
I just realize that dropzone was more than enough for me. So I focused on the dropzone instead on the file input. I really don't like the browsers default file input, drop zone its cool. I just wanted to provide both ways but I stick with dropzone as default and only file input component.

**Comment by arivera12** [comment]
But adding this feature for others may be cool or needed for them.
