### ISSUE TITLE
Feature Request: Add Click method to IFileReaderRef

### ISSUE THREAD

**Issue by EduVencovsky** [Tewr/BlazorFileReader#136]
This is feature request is very simple, just add a method to enable you to programmatically click on the input so it open's the window to choose the files.

I could do this by just calling 

    await JSRuntime.InvokeVoidAsync("clickOnElement", Ref);

And creating 

    window.clickOnElement = function(el){ if(el) el.click() }

But I think this would be a very good feature for this library to handle, because it's a very common case where you want to have another button to open the file's window.

Edit
===

The name of the method isn't important here, I think you can decide if it will be named `Click` or whatever, but the feature of that method is important

**Comment by Tewr** [comment]
Thank you for the suggestion. I see the use case, but I don't think its a good fit.

**Comment by EduVencovsky** [comment]
Can you explain why? Just so I can understand what are your plans for this library

**Comment by Tewr** [comment]
I try to keep the API as small as possible while balancing with as many features as possible regarding primarily FileReader and streams. I try to stay away from the DOM. Thus with the exception of file input and generic drop targets cause I don't really feel like I have a choice.

This could possibly be part of the drag and drop example, but as a part of the library it's feels like a stretch. It's a use case for sure, but not really related to files or streaming.

Isn't there some other small library who does this, like... Element extensions or something?
