### ISSUE TITLE
CancellationToken is never used / checked in ReadAsync

### ISSUE THREAD

**Issue by EduVencovsky** [Tewr/BlazorFileReader#137]
**Describe the bug**
While calling `ReadAsync` and passing a `CancellationToken`, if you cancel the token, it doesn't stop reading.

**To Reproduce**

- Create an  `IFileReference`
- Call `OpenReadAsync`
- Call ReadAsync in a while loop passing a `CancellationToken`
- Cancel the token
- You will see that nothing changes and the while continues to loop 

**Expected behavior**
The while loop stops or throws an exception

**Project type**
Server Side

**Environment**
 - Browser Chrome
 - Version of Blazor.FileReader = 1.5.0.20109
 
**Additional context**
While looking in the code, I found the "leaf" ([here](https://github.com/Tewr/BlazorFileReader/blob/199a7006791d88488da674c52855475a4785319c/src/Blazor.FileReader/FileReaderJsInterop.cs#L117) and [here](https://github.com/Tewr/BlazorFileReader/blob/199a7006791d88488da674c52855475a4785319c/src/Blazor.FileReader/FileReaderJsInterop.cs#L129)) functions that read the file and realized that it doesn't use the `CancellationToken`. 

Also while [searching in the entire repository for `CancellationToken`](https://github.com/Tewr/BlazorFileReader/search?q=CancellationToken), I couldn't find any place where it's used.

I can make a PR to add checking for the `CancellationToken`, but I'm not sure if this feature is really missing or I just couldn't find it.

So please, let me know if this feature doesn't exists and I can work on it, or point out the place where the token is used to check for the cancellation and show what I'm doing wrong.

Here is how I'm doing it.

```
using (var fs = await fileReference.OpenReadAsync())
{
    fs.Seek(0, SeekOrigin.Begin);
    var buffer = new byte[ChunkSize];
    while (await fs.ReadAsync(buffer, 0, buffer.Length, CancellationTokenSource.Token) != 0)
    {
        // do other stuff
    }
}
```

And in other place, when a user clicks on a delete button, I call 

```
CancellationTokenSource.Cancel();
```

**Comment by Tewr** [comment]
This has never been implemented. It's mandatory for the stream override though, so indeed, it's there. As the chain contains a single real async call, not particularly useful in this s case. Might be useful for extension methods like CopyToAsync though, and I agree that it's kind of unexpected that it does nothing.

Easy to implent, but I'm not 100% sure where I'd put the throw. Before or after the Jsinvoke? Both? Unimportant?

**Comment by EduVencovsky** [comment]
I'm not sure what you mean by "Before or after the Jsinvoke".

Do you mean before/after the call to the `IJSRuntime`?

e.g.
```
private async Task<string> ReadFileMarshalledBase64Async(int fileRef, long position, int count, CancellationToken cancellationToken)
{
    // before
    var data = await CurrentJSRuntime.InvokeAsync<string>($"FileReaderComponent.ReadFileMarshalledAsync",new { position, count, fileRef });
    // after
    return data;
}
```

Or do you mean before/after the function that calls the IJSRuntime functions?
e.g. 
On the functions that call `ReadFileMarshalledBase64Async` and `ReadFileUnmarshalledAsync` 

----

If it's the first case, I think that ou should throw before `CurrentJSRuntime.InvokeAsync` to avoid unnecessary call to javascript.
If it's the second case, I if my assumptions are correct and `ReadFileMarshalledBase64Async` and `ReadFileUnmarshalledAsync` are the "leaf" function to javascript (the only functions that call javascript), you should call in that functions, to avoid having to throw in multiple functions.   

Something like 

```
private async Task<string> ReadFileMarshalledBase64Async(int fileRef, long position, int count, CancellationToken cancellationToken)
{
    cancellationToken.ThrowIfCancellationRequested();
    var data = await CurrentJSRuntime.InvokeAsync<string>($"FileReaderComponent.ReadFileMarshalledAsync",new { position, count, fileRef });

    return data;
}
```

**Comment by Tewr** [comment]
Now that I'm on a computer I can see that the all the `JSRuntime.InvokeAsync` has an overload for this. 

From the method docs:
```
/// A cancellation token to signal the cancellation of the operation. Specifying this parameter will override any default cancellations such as due to timeouts
/// (<see cref="JSRuntime.DefaultAsyncTimeout"/>) from being applied.
```

Permits the cancellation of the actual underlying task. Sounds good I think.

**Comment by Tewr** [comment]
`WebAssemblyJSRuntime.InvokeUnmarshalled` does not handle this though.

**Comment by EduVencovsky** [comment]
I never used `CancellationToken` before so I'm not sure how that would work, I will study more about it and how it works. But I think this is a nice feature to implement.

**Comment by Tewr** [comment]
This feature will be part of next release.
