### ISSUE TITLE
Very slow file reading

### ISSUE THREAD

**Issue by waleedcordy** [Tewr/BlazorFileReader#141]
I am trying to build a Blazor WASM application, basically it uses your component as a file reader then I would forward the files to a SHA-256 hashing method, the main issue happens whenever I try to read large files > 10mb , it takes about 40 seconds to just read it , do you have any clue about what happens ?

**Comment by Tewr** [comment]
Hello! 

I think the best way is to use a Stopwatch or performance counter to see what's taking long.

That said, SHA-256 is painfully slow on the platform, and has little to do with reading files. If I load a 7mb file into a byte array first, it takes 55ms. The Sha-256 hash of that byte array takes 13 seconds. Using the sequential method, reading the file in chunks, yields about the same result, with a small overhead for chunking, something like 14 seconds in total.

**Comment by waleedcordy** [comment]
I already tried the stopwatch method once, I even removed the Hashing method to analyse what causes the long time taken , up until now it is not a hashing issue.
55ms !! , this is interesting, what's your configuration for this ?

**Comment by waleedcordy** [comment]
You are absolutely right , turns out it is my fault with my setup.
