### ISSUE TITLE
Out Of memory thrown when attemting to open a MemoryStream into an 840MB file

### ISSUE THREAD

**Issue by Smurf-IV** [Tewr/BlazorFileReader#146]
**Describe the bug**
```
System.OutOfMemoryException: Out of memory blazor.webassembly.js (1,37691)

  at System.IO.MemoryStream.set_Capacity (System.Int32 value) <0x30a33f0 + 0x00086> in <filename unknown>:0 blazor.webassembly.js (1,37691)

  at System.IO.MemoryStream.EnsureCapacity (System.Int32 value) <0x30a31b8 + 0x000a2> in <filename unknown>:0 
blazor.webassembly.js (1,37691)

  at System.IO.MemoryStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) <0x30a2dc0 + 0x000de> in <filename unknown>:0 blazor.webassembly.js (1,37691)

  at System.IO.MemoryStream.WriteAsync (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.Threading.CancellationToken cancellationToken) <0x3859260 + 0x000ae> in <filename unknown>:0 
blazor.webassembly.js (1,37691)

--- End of stack trace from previous location where exception was thrown ---
blazor.webassembly.js (1,37691)


blazor.webassembly.js (1,37691)

  at Blazor.FileReader.FileReference.InnerCreateMemoryStreamAsync (System.Int32 bufferSize) <0x383c088 + 0x00216> in <filename unknown>:0  blazor.webassembly.js (1,37691)

  at Blazor.FileReader.FileReference.InnerCreateMemoryStreamAsync (System.Int32 bufferSize) <0x383c088 + 0x003f2> in <filename unknown>:0 
```

**Project type**
Client Side Blazor

**Environment**
 - Browser [Edge]
 - Version of Blazor.FileReader Latest
 - Version of .net sdk 2.1
 
**Additional context**
Trying to read into 1MB chunks but it never succeeded on the first one for this large file.

**Comment by Tewr** [comment]
Hello!

"Trying to read into 1MB chunks but it never succeeded on the first one for this large file." - I don't really see what you mean. Was there an error? what are you trying to do?

If you show me your code I might be able to help you. 
Indeed, reading in such a large file into memory is apparently problematic, seems like the runtime won't have it. Use chunking instead.

**Comment by Smurf-IV** [comment]
Apologies, it was a long day for me, and even re-reading I understand your comments. Lets start again.
Scenario with Version `1.6.0.20166`:
- multiple files, each with their own filerReader instance (Stored in `FileSelect`)
- first file of 250Mb is opened via file stream with the intention of sending to the server in 1MB chunks
- spin, spin, spin, All good, dispose of memory and filestream, force `GC.Collect() and Finalizer()`, move to next file
- 2nd file is 840MB, same process, but before it can read the first MB out of the stream (see `stream.ReadAsync`) the above memory exception is thrown, It appears that it is using the internal MemoryStream doubling allocation, when I have forcible set a buffer of 64K (I was under the impression that this prevents the whole file from being loaded into memory, like it does with `W8lessLabs.Blazor.LocalFiles`)

Code snippets to show the above (Failure happens at the first line!):
```Csharp
await using var stream = await fileInfo.FileSelect.CreateMemoryStreamAsync(bufferSize: 64*1024);    // Keep below LOH
int numBytesRead;
byte[] buffer = new byte[CHUNK_SIZE];
while ((numBytesRead = await stream.ReadAsync(buffer, 0, CHUNK_SIZE, cancellationToken)) > 0)
{
    // Re-use existing code
    var payloadRequest = CreatePayloadRequest(ref buffer, numBytesRead);
    var payload = new AppendPayloadRequest { Payload = payloadRequest.Payload, Reference = reference };
    await AppendCallAsync(payload, cancellationToken);
    // Need to handle the following
    /*L: GC_MINOR: (user request) time 2.60ms, stw 2.80ms promoted 55K major size: 5456K in use: 4387K los size: 1110784K in use: 1105734K blazor.webassembly.js (1,37691)
    Boom -> System.OutOfMemoryException: Out of memory
                */
    const long M_BYTE756 = 1024L * 1024 * 756;
    long totalBytes = GC.GetTotalMemory(false);
    if (totalBytes > M_BYTE756) // When above 840Mb, things start to go awry!
    {
        GC.Collect(1, GCCollectionMode.Forced); // Try and reclaim as quick as possible
    }
    await Task.Delay(1, cancellationToken); // give it chance to go / or throw exception due to signature etc. / or GCollect
    fileInfo.Progress.ReportProgress(fileInfo.Progress.CurrentRawValue + numBytesRead);
}
// Force closure of jsInterop / blobs / other memory
await stream.DisposeAsync();
fileInfo.File = null;
fileInfo.FileSelect = null;
// Force tidy-up of jsInterop / blobs / other memory
GC.Collect();
// Wait for all finalizers to complete before continuing.
GC.WaitForPendingFinalizers();
Console.WriteLine("[{0}] UploadFilesAsync: End [{1}]", DateTime.UtcNow, fileName);
```

**Comment by Smurf-IV** [comment]
I removed the buffer value, And i have just noticed that the code "double allocates the filesize" before moving to the next line:
i.e. the `CreateMemoryStreamAsync` allocates twice the file size, and when it then completes, it releases the other half.
![image](https://user-images.githubusercontent.com/2418812/87756810-7f086300-c801-11ea-957e-d210b5a4a6cb.png)
The highlighted lines are either side of the `CreateMemoryStreamAsync` call

**Comment by Smurf-IV** [comment]
I can now see what you were doing in the code.
Some suggestions, take it or leave them.
- deprecate the following `public Task<MemoryStream> CreateMemoryStreamAsync(int bufferSize)` with a comment stating that MemoryStream returned will be the size of the file
- change the `InnerCreateMemoryStreamAsync` function to:
  - always take the file size
  - remove the `byte[]` allocation
  - remove the while loop and use `CopyToAsync(Stream destination);`
- Change the description of the `CreateMemoryStreamAsync` to state that the memory stream will be the file size and the position will be at 0
- Improve the descriptions of the `OpenReadAsync()` to state that this is forward only stream equivalent to a Stream directly on the file
- remove the '$' from the begining of strings and use '@' ('$' means `string.Format()`, which are not doing)

**Comment by Tewr** [comment]
Thanks for the feedback! 

My thoughts:

> deprecate the following public Task<MemoryStream> CreateMemoryStreamAsync(int bufferSize) with a comment stating that MemoryStream returned will be the size of the  file

For me "reading the file into memory" implicits that the Memory stream will be the full size of the file. But I also fully agree that the documentation is short and could be more explicit for both methods.

However, deprecation I can't agree with. 
There is a big difference between this method and the 
CreateMemoryStreamAsync() in ram usage for large files. Ex: File of 400Mb and 1mb chunk size using CreateMemoryStreamAsync(buffersize:1Mb)  has a theoretical ram usage peak of 400mb (memory stream)+1mb(JavaScript chunk, native allocation)+1mb(byte array copy) during the operation. .net will see 401mb.

File of 400Mb and 400mb chunk size using CreateMemoryStreamAsync(buffersize:400Mb) (what  CreateMemoryStreamAsync() does)  has a theoretical ram usage peak of 400mb +400mb+400mb.
.net will see 800mb, 400mb of the native allocation can only be seen in the OS process allocation, and varies a bit between browsers implementations. This method is a lot faster though, and really the best choice for smaller files.

In any case, both of these methods are clearly convenience methods, far from necessary in the library...and are certainly not suitable for large files. I did mention that for one of the methods in the readme but API documentation is the best for sure.

**Comment by Tewr** [comment]
> change the InnerCreateMemoryStreamAsync function to:
> always take the file size
> remove the byte[] allocation
> remove the while loop and use CopyToAsync(Stream destination);

Indeed, I'm not sure why I'm doing this. It's probably the exact same code as in CopyToAsync. But you won't win anything other that pretty code, CopyToAsync does a byte alloc internally..
