### ISSUE TITLE
Blazor 0.9.0 support

### ISSUE THREAD

**Issue by IvanJosipovic** [Tewr/BlazorFileReader#15]
https://devblogs.microsoft.com/aspnet/blazor-0-9-0-experimental-release-now-available/

To upgrade a Blazor 0.8.0 project to 0.9.0:

    Update the Blazor packages and .NET CLI tool references to 0.9.0-preview3-19154-02.
    Update the remaining Microsoft.AspNetCore.* packages to 3.0.0-preview3-19153-02.
    Remove any usage of JSRuntime.Current and instead use dependency injection to get the current IJSRuntime instance and pass it through to where it is needed.

**Comment by christiandersendk** [comment]
This is properly a stupid question, but how do i detect the usage of JSRuntime.Current and how do i remove it? To follow these instructions: Remove any usage of JSRuntime.Current and instead use dependency injection to get the current IJSRuntime instance and pass it through to where it is needed.

**Comment by Tewr** [comment]
@christiandersendk : The instructions in this issue's top post was copied by @IvanJosipovic from the general upgrade guide (linked in his post). They are the same for any project which were created before 0.9.0. 

Thus, as this project has been upgraded, version 0.9.0-preview-13032019 of BlazorFileReader no longer contains any references to JSRuntime.Current. To use it, just follow the instructions in the readme, whatever's in this issue can be ignored. Does that answer your question?
