### ISSUE TITLE
No Files fetched by EnumerateFilesAsync()

### ISSUE THREAD

**Issue by noumanqaiser** [Tewr/BlazorFileReader#171]
**Describe the bug**
I was trying to use BlazorFileReader in a Blazor Server App. I used the code provided in the example. No matter what type or size of file I select, the function EnumerateFilesAsync() yeilds no files.

**To Reproduce**
As explained above. The following is the debugging view of the files object:
![image](https://user-images.githubusercontent.com/5542052/103630576-4ef17f80-4f5b-11eb-874e-fdea9a0c4cd3.png)

**Expected behavior**
As happening in the Demo project, the files object should contain details of files being read and allow the downstream loop to oterate over the files and obtain their content.

**Screenshots**
Given Above.

**Project type**
**'Server-side'/'SSB'**

**Environment**
 - Browser [e.g. chrome
 - Version of Blazor.FileReader : tried both Nuget Package version 2.1 and 3.0 and both displayed same results.
 - Version of .net sdk .NET Core 5
 
**Additional context**
NA

**Comment by Tewr** [comment]
Hello, thank you for your feedback.

Unfortunately I do not have enough info to help you. Your are describing the most basic usage scenario, which is working well for me and many other package consumers. Try to post some more source code and try to boil it down to the most simple example possible. Include all relevant lines such as using statements and your input element, and I might be able to figure out what is happening. You say you used the code in the example -- I am guessing you are referring to the brief example in the readme. It works well, but a more complete example is in the demo project, specifically [here](https://github.com/Tewr/BlazorFileReader/blob/master/src/Demo/Blazor.FileReader.Demo.Common/IndexCommon.razor).

The only explanation I can think about without seing more of your code is that your `inputTypeFileElement` might be referencing something you are not expecting, not the input you clicked?

**Comment by noumanqaiser** [comment]
@Tewr  Thanks for your reply and Happy new Year. 

I was able to find out what was causing the issue. In my application I have a table that would allow users to upload specific files for the app. Each row has its own upload button and it seems multiple rows cannot share the same InputElement(and thats how it should be ideally). If multiple rows in a table share same inputElement, the EnumerateFilesAsync function wont return any files. 

To solve this, use an Array of inputElements linked to each row and now the upload works completely fine. 

![image](https://user-images.githubusercontent.com/5542052/103739648-56726080-500f-11eb-8842-c97549fe1afc.png)

By the way, I need to bring to your attention the file upload performance, I have used the standard Blazor InputFile component and yours, there is a serious performance difference between the too in terms of upload speed.

For a 75MB Excel file, I noticed that the standard InputFile Component would take more than 20minutes while yours would take around 5minutes which is a major upload speed performance difference. On top your samples allow straight forward upload progress tracking.

Thanks for the inpirational work you are doing!

**Comment by Tewr** [comment]
I'm glad you found the solution! 

Sound odd that the standard component would be slower than mine as normally it trades in the server ram for speed. Mine can normally accomplish the same behavior by setting the buffer size to the file size. On the other hand, it's not the exact same multithreading strategy used, maybe mine has some unexpected advantage. In any case, good news I guess.

I'm closing this then. Happy new year to you too, and happy coding!
