### ISSUE TITLE
Indexes and Removing Files after selection

### ISSUE THREAD

**Issue by zeidoo** [Tewr/BlazorFileReader#172]
Hi,

Wanted to thank you for this control. It's of great use.

I'm not sure if there's a way to do these already, but here goes.

I'm using Server Side Blazor without MVC. I would like to compute the SHA256 hash of the files on the client side so that the files don't go the server. Because I'm using server side Blazor, I've written a small JS function that uses CryptoJS to compute the hash like this.

```
async function createHash(containerEl, index) {
    let file = FileReaderComponent.GetFiles(containerEl)[index];
    return await sha256(file);
}
````

And I call it from C# code like this:
```
// file is an instance of IFileReference
var index = file.GetType().GetField("index", BindingFlags.NonPublic | BindingFlags.Instance)?.GetValue(file.File);

// element is an instance of ElementReference from <div @ref=_dropTargetElement ... >
var hsh = await _js.InvokeAsync<string>("createHash", element, index);
```

This unfortunately uses reflection. Is there a better way to do this?

Secondly, how would I go about removing certain files from the container element? 

For example, after I drag and drop some files on the control, I put them into a collection using `var files = await _dropReference.EnumerateFilesAsync();` Then I can use this collection to show the file names to the user or use the items in this collection to read the actual file data. The user can interact with this collection to remove files added by mistake during the selection process.  However, after removal from this 'view' collection, this 'view' collection and the files in the container element are out of sync. If the user drag and drops some files again, the `_dropReference.EnumerateFilesAsync()` method will return files that the user previously added/removed in addition to the newly added files.

Of course I could clear the container element files with ` _dropReference.ClearValue();` but then, I think the index proeprty stored in a IFileReference becomes invalid, so if the user wants to read the files contents from a IFileReference object stored in a variable somewhere, it gives `Unhandled exception rendering component: No FileList available.` or an index out of bounds. or even worst, it may read the data from the wrong index/file.

**Comment by Tewr** [comment]
First question: no, there is no supported way of interacting with file instances "outside" of the library in javascript. It's an interesting use case, but probably not something a lot of people will use. Still, I will consider it for a future release.

**Comment by Tewr** [comment]
As for your second question, the code in the example here:
https://github.com/Tewr/BlazorFileReader/blob/master/src/Demo/Blazor.FileReader.Demo.Common/DragnDropInputCommon.razor

answers your question about managing removal etc.
 
The "trick" is to open a file stream directly when the user drops a file. This will create/save a reference to the file in javascript, so you no longer depend on the index to read the file, even if you called clear() on the element.

**Comment by zeidoo** [comment]
Hey, thank you for your replies.

Opening up the stream did seem to work, but I have to play around a bit more to see if everything is okay.

As for obtaining js object references the following seemed to work for my use case:

```
var jsFileList = await Js.InvokeAsync<IJSObjectReference>("FileReaderComponent.GetFiles", _dropTargetElement);

foreach (var file in await _dropReference.EnumerateFilesAsync())
{
    var index = file.GetType().GetField("index", BindingFlags.NonPublic | BindingFlags.Instance)?.GetValue(file);
    var jsFile = await jsFileList.InvokeAsync<IJSObjectReference>("item", index);
}
```

Then the jsFile var can be passed around to another js function from a  completely different part of my C# code (in my case, a Fluxor effect)

```
 var module = await _js.InvokeAsync<IJSObjectReference>("import", "./js/hashing.js");
 var hash = await module.InvokeAsync<string>("hasher.sha256", action.Picture.JsFile); <-- action.Picture.JsFile is the jsFile var above
```

I think I have to manually release the js object references once I'm done with them, but I'm not there yet.

**Comment by Tewr** [comment]
I'd recommend passing around the `Stream` from `OpenRead` instead. It is mapped to a javascript `File`, which will be released when you dispose the Stream. It is indexed by the private field `fileRef`, and the references are in `FileReaderComponent.fileStreams`. It's a little bit less fragile. You would still have to use reflection to get the private field though, so you're still in for possible breaking changes in future versions

**Comment by Tewr** [comment]
Closing in favour of #173
