### ISSUE TITLE
Support for URL.createObjectUrl(file)

### ISSUE THREAD

**Issue by njannink** [Tewr/BlazorFileReader#175]
When using the BlazorFileReader in combination with eg a image preview component you would like to have support for `URL.createObjectURL`, because big images eg a high res image from your phone cant be read as a base64 string.

See: https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

I would be nice if on the api of `IFileReference` you will have a call `CreateObjectURL`

**Comment by Tewr** [comment]
available in release 3.1
