### ISSUE TITLE
Is it possible to access the files property of event.clipboardData in paste event?

### ISSUE THREAD

**Issue by markjerz** [Tewr/BlazorFileReader#179]
Hi,

Having read through the code, I think the current answer to this is "no". It looks like the FileReaderComponent can only access the files property on a file input or any DataTransfer objects captured during drag and drop.

I don't think there's any way of hacking around the current release to make it work?

It should be fairly quick to implement the solution in a similar way to the drag and drop solution. Using the `elementDataTransfers Map<HTMLElement, FileList>` inside the FileReaderComponent but modifying that through a paste event instead? 

 I might be able to put together a PR if that's something that you'd be happy to add?

**Comment by Tewr** [comment]
Sounds great. To be honest I was fully unaware to this API. There's a plugin API to modify the drag and drop events but having looked at your PR, this being a separate event, I'd agree your implementation is the way to go.

**Comment by Tewr** [comment]
implemented in #180
