### ISSUE TITLE
ReadFileInfoAsync() can't read file size properly for large files

### ISSUE THREAD

**Issue by ayinesk** [Tewr/BlazorFileReader#182]
I'm working on file uploading using BlazorFileReader and I need to test uploading file larger than 500 MB.

I've created the test file using this command:
    **fsutil file createnew D:\File500.ocx.xz 525336576**

File properties:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/23136743/137080112-c1a2235d-61b8-48b0-bc51-def6be2bfe78.png)

File size is 501 MB

Then I tried to read it using BlazorFileReader

![testCode](https://user-images.githubusercontent.com/23136743/137080390-70edda40-808c-466e-ad8b-3b21679483cf.png)

And **fileInfo** size is 500 MB instead of 501 MB

![locals](https://user-images.githubusercontent.com/23136743/137080624-532899fa-6224-4a2c-84d4-4c5d12ee90ce.png)

Tewr.Blazor.FileReader Version 3.2.0.21211

**Comment by Tewr** [comment]
Hello. This seems odd. 

The size is not calculated or anything, comes straight out of the native property size here:
https://github.com/Tewr/BlazorFileReader/blob/6c2f0ef3884d5e303092debaf4898d06dde3f2a0/src/Blazor.FileReader/script/FileReaderComponent.ts#L92-L98

So the possible sources of this errors I could think of are (in my orderof probablilty): 
1) Something with your environment
2) Browser bug
3) The Int64 [file.size](https://github.com/Tewr/BlazorFileReader/blob/6c2f0ef3884d5e303092debaf4898d06dde3f2a0/src/Blazor.FileReader/FileReaderRef.cs#L191) is serialized incorrectly when moving from js to .net

First of all, 
Are you using Server-side (asp.net) or Client-side (Web-assembly) Blazor?

**Comment by Tewr** [comment]
I tried your command and used the live demo on https://tewr.github.io/BlazorFileReader/ to try it
![image](https://user-images.githubusercontent.com/2945607/137134416-94c768fe-3524-4e6b-bd30-b17d0dfc8fd4.png)

![image](https://user-images.githubusercontent.com/2945607/137133741-f8120bfb-49d4-4a79-9b8e-399c98cea2d4.png)

Works as expected as least on WebAssembly. Could you try the online demo as well to see what you get? Maybe something fishy with the debugger in Visual Studio?

**Comment by Tewr** [comment]
Closing this. Feel free to reopen if you have any new info.
