### ISSUE TITLE
.Net 6 compatibility

### ISSUE THREAD

**Issue by jerryhonda** [Tewr/BlazorFileReader#183]
tried the demo code with .Net 6,
But the buffer from stream.ReadAsync are all byte 0, but the file length is correct.

**Comment by kamilfras** [comment]
Hi, @Tewr I have the same problem. When are u planning to fix this issue ? If not in the few next days i should concider use other library xD

**Comment by Tewr** [comment]
Hello,
I'm clearly lagging in .net6 support, the changes to the underlying components being used is quite radical. Even though the fix might be relatively easy as there are now framework primitives for streaming (https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.ijsstreamreference?view=dotnet-plat-ext-6.0) , I can't pronouce myself on any planning on a .net6 compatible release. 

Pull requests are welcome.

**Comment by kamilfras** [comment]
Thank you for the answer 👍
