### ISSUE TITLE
Fail after move to iis

### ISSUE THREAD

**Issue by HelvioMarkman** [Tewr/BlazorFileReader#185]
I am using to send pictures from Blazor Wasm Client to a Database. It works really well when is running in the project with multiple projects execution, but when I moved to IIS start to have Cors error. 
The cors police:
options.AddPolicy(name: MyAllowSpecificOrigins,
                                  builder =>
                                  {
                                      builder
                                      .AllowAnyHeader()
                                      .AllowAnyOrigin()
                                      .AllowAnyMethod();                                      ;
                                  });

![image](https://user-images.githubusercontent.com/20973414/146604432-af958bc8-cd9e-416e-9625-fe3779a9c020.png)

Please can you help me.

**Comment by Tewr** [comment]
Hello. This does not sound related to this component. Try StackOverflow for help.

That said, If you are getting a CORS error when using HttpClient when trying to send the image, the correct CORS configuration needs to be on the receiving side. Don't hesitate provide (a lot) more code on both client and server side, and any error you get in the network tab, the info you have provided, is at least for me to help out, very sparse.
