### ISSUE TITLE
Unable to read a file stream of size greater than 512KB when using BlazorFileReader with .NET 6

### ISSUE THREAD

**Issue by josephsleiman16** [Tewr/BlazorFileReader#188]
I get the following error when attempting to read a file using CreateMemoryStreamAsync with BlazorFileReader and .NET 6:

![image](https://user-images.githubusercontent.com/60473095/221150109-b4687083-cbcd-42e1-b5e9-a69ba31b6d3f.png)

The [OpenReadStreamAsync ](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-7.0#stream-from-javascript-to-net) function has a parameter 'maxAllowedSize' with a default of 512000 (512KB) and this default is being utilised within the following: 
https://github.com/Tewr/BlazorFileReader/blob/c9a2f9fa147f627a8b409a09bbd239bef21f0028/src/Blazor.FileReader/FileReaderJsInterop.cs#L208-L218

Could I request a 'maxAllowedSize' parameter be added to maybe a new CreateMemoryStreamAsync overload, or a new method along the lines of "CreateMemoryStreamWithSizeLimitAsync" (to avoid overload issues with the same parameter types), and then passed to OpenReadStreamAsync so that users on .NET 6 or greater can set a custom file size limit - 512KB is quite limiting.

**Comment by Tewr** [comment]
Hello, thank you for your feedback.

As stated in the [readme]( https://github.com/Tewr/BlazorFileReader#ifilereferencecreatememorystreamasync) here, calling `CreateMemoryStreamAsync` without any argument is a bad idea for big files. I must say I didn't know it would crash in .net6 though, it just used to be slow to the point of unusable to have a too large buffersize (by default it equals that of the file itself). Also maybe it was a poor api decision to set the buffersize by default to filesize, for this method, but for small files it is the fastest and simplest option. I guess the new default should be Math.Min(512kb, filesize) in .net6...

Try calling `CreateMemoryStreamAsync` with the overload for `bufferSize`, and set it to someting lower than 512Kb, like 256kb maybe, see if it works better for you.

**Comment by josephsleiman16** [comment]
Hi, thank you for your quick response.

I saw the readme after posting this issue and implemented my solution using the Microsoft InputFile component you mentioned which seems to fix the issues I had using NET 6. 

Your solution of overloading the `bufferSize` also seems to work and prevent the crash with something like `CreateMemoryStreamAsync(bufferSize: 256000)`, so I will close this issue.
