### ISSUE TITLE
Drag+Drop does not work with additive drop file list

### ISSUE THREAD

**Issue by DNF-SaS** [Tewr/BlazorFileReader#194]
When using Drag+Drop and additive filelist feature, IFileReaderRef.EnumerateFilesAsync() does not return.
Repro possible by passing 'true' to RegisterDropEventsAsync() in DragnDropDivCommon.razor (Line 69) - startup-project is Demo/Net/Blazor.FileReader.ServiceSide.Demo
Problem exists since 3.3.2.23185 (3.3.1.21360 is working fine)

**Comment by Tewr** [comment]
Thank you for the bug report. This was clearly missed in the tests after the last feature PR. I desperately need to get the automated tests back up working...
