### ISSUE TITLE
Server-side projects has a max buffer-size of 2895 bytes

### ISSUE THREAD

**Issue by Tewr** [Tewr/BlazorFileReader#24]
Since 3.0.0 preview 4, Server-side blazor Json Serialization fails with a not very descriptive exception if the signalR message is too large (over 2895), and when set lower, sporadically:

after this function call: https://github.com/Tewr/BlazorFileReader/blob/5a733702d9920e2760245b14f3675b67afd4c192/src/Blazor.FileReader/content/FileReaderComponent.ts#L167

which calls
https://github.com/Tewr/BlazorFileReader/blob/5a733702d9920e2760245b14f3675b67afd4c192/src/Blazor.FileReader/content/FileReaderComponent.ts#L171

we get this:

```

Uncaught (in promise) Error: System.Runtime.Serialization.SerializationException: Invalid JSON string
   at SimpleJson.SimpleJson.DeserializeObject(String json)
   at SimpleJson.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy)
   at SimpleJson.SimpleJson.DeserializeObject[T](String json)
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
    at endInvokeDotNetFromJS (blazor.server.js:8)
    at blazor.server.js:8
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (blazor.server.js:8)
    at blazor.server.js:1
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (blazor.server.js:1)
    at e.processIncomingData (blazor.server.js:1)
    at e.connection.onreceive (blazor.server.js:1)
    at WebSocket.i.onmessage (blazor.server.js:1)
endInvokeDotNetFromJS @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
beginInvokeJSFromDotNet @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1

```

Not really clear if this is happening on the server or on the client, but I suspect the client as the task on the server never resolves.

Seems that with an even lower buffer size, like 2000, it never happens.

Anything over 3000, it happens all the time. Fun stuff!

**Comment by MyNameIsDonovan** [comment]
This was working fine before the new preview :(
Looks like other people are running into it as well
https://github.com/aspnet/AspNetCore/issues/9570

**Comment by Tewr** [comment]
Thank you for the link! The "Sporadical" part is most likely the framework metadata in the signalr message which seems to have a slightly different size for each message. I'm going to update the server-side example to use 2000 as default chunk size to be on the safe side, for now. Not very nice though, I hope they come up with a fix for next release.

**Comment by MyNameIsDonovan** [comment]
Yeah it seems the metadata can vary, even for the same image.
Its funny because it also seems to vary browser to browser. On edge, I can only upload super small images 3-4kb, and that works maybe 50% of the time. I can get larger files to work with smaller chunk sizes on chrome to work about 70% of the time.

**Comment by tmayonez** [comment]
How do you implement  chunking? Is there any signalR setting for this?

**Comment by Tewr** [comment]
@tmayonez: No, this is not signalR. I am just limiting the size of an interop callback. The actual chunking is being done here: https://github.com/Tewr/BlazorFileReader/blob/5a733702d9920e2760245b14f3675b67afd4c192/src/Blazor.FileReader/content/FileReaderComponent.ts#L143

The method, `ReadFileMarshalledAsync`, is only used by Server-side blazor projects. It _could_ be used by client-side projects as well, but as an optimization the client side rather calls `ReadFileUnmarshalledAsync`, which uses unmarshalled copy of the raw bytes into the mono runtime rather than data url

**Comment by pfeurean** [comment]
does this issue also explain why the webserver process exits (kestrel/iisexpress) once a file is selected. when running in wasm mode, the app keeps responding correctly but the server is just dead from there on.

**Comment by Tewr** [comment]
I'm not sure. Please try the latest release as the improved error management in #30 should make exceptions bubble up correctly in server-side projects. In any case, the issue described in this ticket is a server-side only problem, I have not seen it in WASM.
