### ISSUE TITLE
Tewr.Blazor.FileReader leaks js files into project

### ISSUE THREAD

**Issue by IvanJosipovic** [Tewr/BlazorFileReader#34]
When adding Tewr.Blazor.FileReader 0.10.19116 to a Blazor Client Side project it leaks the "content" folder into the project.

![image](https://user-images.githubusercontent.com/9521987/57154985-11545080-6d8f-11e9-8e81-9161a0733b10.png)

Repro Steps:

1. Create Blazor project

1. Add "Tewr.Blazor.FileReader" 0.10.19116 Nuget package

**Comment by Tewr** [comment]
That's odd, must have been a slip on my part in the upgrade process. I could have gotten away with "its a feature not a bug", if it wasn't for the fact that it's in the wrong folder :)
