### ISSUE TITLE
Unable to reset the file picker

### ISSUE THREAD

**Issue by JoacimWall** [Tewr/BlazorFileReader#35]
Hi 
I am new to html  
I use this file picker and it works good but i need some way to reset/clear it.
I have global save button where i save difrent propertys on a object where i also save the file to azureblob. the problem is that the control keep the file refrens så on very save i add a new version of the same file to the azureblob storage.

**Comment by Tewr** [comment]
Hi.
The naive way would be to use `bind="@inputValue"` on the input and when it's time to reset, you just set `inputvalue = ""`.

However I tried, and it works on chrome but crashes on Microsoft Edge. It's most likely a bug (may be related to the fact that `value` of the `input` behaves a bit different on `input type=file`), so I'll file a bug for the blazor team to look at it.

So an alternative solution working around this bug would be interoping to reset the value. You would do like this: 
1) in the bootstrap html (wasm: `wwwroot/index.html`, server-side: `Pages/_Host.cshtml`) put the following code at the end of body: `<script>window.emptyInputValue= function (input) { input.value = ''; };</script>`

2) whenever you are ready to reset the file from your c# code, you call
`await jsruntime.InvokeAsync<object>("emptyInputValue", inputElement);`
where `inputElement `is the `ElementRef` bound to the input tag, and `jsruntime` is a reference to IJSRuntime, in a razor file you can get it by declaring `@inject IJSRuntime jsruntime;` at the top of the file.

I think I'll add this method to the library, as I realize this is a bit clunky and could be useful.

**Comment by JoacimWall** [comment]
Thanks
i use the bind soultion. this is a internal demo app for now so Chrome is requered.

//Regards Joacim
