### ISSUE TITLE
Drag & drop

### ISSUE THREAD

**Issue by Tewr** [Tewr/BlazorFileReader#51]
@catlan : Thank you for your PR. I'm having trouble firing the drop event using your example. The browser default event is fired (file opens in browser when dropped on element, as if ev.preventDefault() is never called)

Do you have a full example on how to use the code you provided to share?

I tried with preview7.

Regards

**Comment by catlan** [comment]
Just on my phone right now, but I believe this is the reason:

Typically, an application will include a dragover event handler on the drop target element and that handler will turn off the browser's default drag behavior. To add this handler, you need to include a ondragoverglobal event handler:

function dragOverHandler(ev) {
// Prevent default behavior (Prevent file from being opened)
ev.preventDefault(); }

**Comment by Tewr** [comment]
Excellent catch! This was indeed the source of the problem. I'm going to add a prevent default dragover handler as well in the initial code. The idea is that package consumers write as little javascript as possible! unfortunately, it is not possible to do preventDefault in Blazor/c# yet, [it must be done with js interop](https://github.com/aspnet/AspNetCore/issues/5545)
