### ISSUE TITLE
Unable to use file read with server-side preview6

### ISSUE THREAD

**Issue by tmarkovski** [Tewr/BlazorFileReader#54]
**Describe the bug**
Can't use the file reader component with server side Blazor. The signalr connection fails. On the backend side, the code just hangs when attempting to read from the stream at `await stream.ReadAsync`
Due to other dependencies with the project, I'm unable to use net 3.0 preview7 at this time.

**To Reproduce**
Pretty much using the suggested code to reproduce this.

```
public async Task<string> GetImagePathAsync()
{
    foreach (var file in await FileService.CreateReference(FileElement).EnumerateFilesAsync())
    {
        var fileInfo = await file.ReadFileInfoAsync();
        using var stream = await file.OpenReadAsync();
        var imageData = new byte[stream.Length];
        await stream.ReadAsync(imageData, 0, (int)stream.Length);

        using var imageStream = new MemoryStream(imageData);
        return await Client.UploadImageAsync(imageStream, fileInfo.Name, fileInfo.Type);
    }
    return null;
}
```

**Project type**
Server-side

**Environment**
 - Browser: Safari, Firefox and Chrome
 - Version of Blazor.FileReader - 0.12.19186
 - Version of .net sdk - 3.0.100-preview6-012264

**Comment by tmarkovski** [comment]
Closing this, as I figured it out. The issue was the buffer size limit of 4096 when reading the stream. Working code below in case anyone runs into again.

```
public async Task<string> GetImagePathAsync()
{
    foreach (var file in await FileService.CreateReference(FileElement).EnumerateFilesAsync())
    {
        using var stream = await file.OpenReadAsync();
        var fileInfo = await file.ReadFileInfoAsync();
        var imageData = new byte[stream.Length];

        int count;
        var buffer = new byte[4096];
        while ((count = await stream.ReadAsync(buffer, 0, buffer.Length)) != 0)
        {
            Array.Copy(buffer, 0, imageData, stream.Position - count, count);
        }

        using var imageStream = new MemoryStream(imageData);
        return await Client.UploadImageAsync(imageStream, fileInfo.Name);
    }
    return null;
}
```

**Comment by Tewr** [comment]
@tmarkovski great that you found a solution.

However, I think your code is equivalent to just calling
 `var imageStream = await file.CreateMemoryStreamAsync(4096)`;

In preview 7, using the [solutions posted here](https://github.com/aspnet/AspNetCore/issues/9570), should work, but if you're stuck in preview6 solutions above will have to do.

**Comment by tmarkovski** [comment]
I was not aware of that method. Thank you!
