### ISSUE TITLE
Progress callback

### ISSUE THREAD

**Issue by PhilPJL** [Tewr/BlazorFileReader#57]
Not a bug - a request.  Can we have notification of progress during the upload?

I have code like this:

```
            try
            {
                using (var stream = await file.CreateMemoryStreamAsync(4096))
                {
                    if (Workbook != null)
                    {
                        Workbook.Dispose();
                    }

                    Workbook = new XLWorkbook(stream, XLEventTracking.Disabled);
                    ....
                }
            }
            catch (Exception ex)
            {
                Output += ex.Message;
            }
```

If would useful for larger file to be notified of progress.  Maybe an event on IFileReference or a callback in CreateMemoryStreamAsync.

**Comment by Tewr** [comment]
This is easily achievable by wrapping the file stream. 

This has come up earlier, like a year ago. I could make an example for sure but I think it's too much clutter for the API/package, I want to keep it as small as possible, focusing on opening and reading a stream. CreateMemoryStreamAsync is already a convenience method that is already borderline, but I felt like I had to add it as people might not be very comfortable with ReadAsync.

In the meantime, use the result of OpenReadAsync and pass it to a wrapper stream. There is a wrapper you can use here: http://mel-green.com/Uploads/ProgressStream.cs

**Comment by PhilPJL** [comment]
Ok I'll look at doing that. Thanks.

**Comment by Tewr** [comment]
@PhilPJL: I noticed now that the link I shared does not override ReadAsync, which would be neccessary (but the code would be more or less the same):

```
        public override async Task<int> ReadAsync(byte[] buffer, int offset, int count)
        {
            var bytesRead = await innerStream.ReadAsync(buffer, offset, count);

            OnBytesRead(bytesRead);
            OnBytesMoved(bytesRead, true);

            return bytesRead;
        }
```
