### ISSUE TITLE
Upgrade to Preview 8

### ISSUE THREAD

**Issue by IvanJosipovic** [Tewr/BlazorFileReader#58]
See Blog for details:
https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8

**Comment by MeMurillo** [comment]
Hi there! I'm also waiting for Ter's update. Because when changing: ElementRef to ElementReference ceased to be compatible with the method: 
IFileReaderRef CreateReference (Microsoft.AspNetCore.Components.ElementRef element);

Thank you.
