### ISSUE TITLE
Update to 0.6.0

### ISSUE THREAD

**Issue by Tewr** [Tewr/BlazorFileReader#6]

**Comment by aloneguid** [comment]
please!

**Comment by Tewr** [comment]
yea I already did this like 10 days ago but I'm unable to build the solution with 0.6.0 referenced. getting the same problem with this pr. I'm guessing you managed to build? which sdk are you using?

**Comment by aloneguid** [comment]
@Tewr it builds under 2.1 SDK just fine. The problem was that demo app references nuget package which is not in nuget when you increase package version, so it has to reference the project instead. I've made the fix and PR now builds on AppVeyor as you can see.

**Comment by Tewr** [comment]
My blazor setup is broken, the mono linker wont work for EPPlus in the demo project. thats why it took so long. But if Appveyor can build it (and link it!), there is a way :P Ill just have to reinstall vs & the sdk I guess
