### ISSUE TITLE
EPPlusCommon.razor issue

### ISSUE THREAD

**Issue by PhilPJL** [Tewr/BlazorFileReader#66]
you have

`                        <th @rowspan="cell.Rowspan" @colspan="cell.Colspan">@cell.Value</th>
`

should be

`                        <th rowspan="@cell.Rowspan" colspan="@cell.Colspan">@cell.Value</th>
`

Also the code will link fine for the server side demo.

**Comment by Tewr** [comment]
Thanks!

> Also the code will link fine for the server side demo.

Indeed, I could add a comment to clarify this.
