### ISSUE TITLE
Base64 stream API

### ISSUE THREAD

**Issue by Tewr** [Tewr/BlazorFileReader#68]
A lower-level api should be created, which exposes the base64-encoded string returned by the FileReader.

The use-case is when the byte-stream once the data has arrived to clr-land is just raw data passed on to something else that requires base64-encoding, such as a cloud service. 

Current process is either a) `file -> byte[] -> base64` (wasm with shared buffer option) or worse b)`file -> base64 -> byte[] -> base64` (for server-side or wasm without shared buffer option).

The process should rather be just `file -> base64`, the first two steps of process b.

**Comment by ADefWebserver** [comment]
For the record, for server side Blazor we are able to upload files, using this component, to Azure storage with blazing performance. So, while the current process may be 'inefficient' I currently have no complaints :)

**Comment by ADefWebserver** [comment]
However I am using this in startup.cs 
```
         services.AddServerSideBlazor().AddHubOptions(o =>
            {
                o.MaximumReceiveMessageSize = 10 * 1024 * 1024;
            });
```

**Comment by Tewr** [comment]
Thanks for the feedback. For server-side apps, the application Max BufferSize + some x (for blazor metadata) must be larger than whatever buffer size is used.  This and the fact that `CreateMemoryStream()` without any argument will use the file size as buffer size, is something that should be documented in the readme as a "gotcha"...

**Comment by Mason742** [comment]
> For the record, for server side Blazor we are able to upload files, using this component, to Azure storage with blazing performance. So, while the current process may be 'inefficient' I currently have no complaints :)

Have you tried uploading to Amazon S3?

**Comment by ADefWebserver** [comment]
> Have you tried uploading to Amazon S3?

No I haven't.

**Comment by Tewr** [comment]
This Api was published in https://github.com/Tewr/BlazorFileReader/pull/76
