### ISSUE TITLE
Uploading file > 30MB on Server-Side Blazor causes "Request body too large"

### ISSUE THREAD

**Issue by hamishfagg** [Tewr/BlazorFileReader#69]
**Describe the bug**
Uploading a file > 30MB results in 
```
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Error: Unexpected exception in "IISHttpContext.ReadBody".

Microsoft.AspNetCore.Server.IIS.BadHttpRequestException: Request body too large.
   at Microsoft.AspNetCore.Server.IIS.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
```
(the error actually happens at about 21.3MB of the file transferred).

**To Reproduce**
1. New server-side project on preview 7 and filereader 0.13.19207
2. Use example async method with stream reading
3. Upload file > 30MB

**Project type**
Server-side

**Environment**
 - Browser: chrome and edge
 - Version of Blazor.FileReader: 0.13.19207
 - Version of .net sdk: 3.0.0-preview7-27912-14
 
**Additional context**
I've tried increasing the signalr message size, but I don't think that's the issue here. IIS is complaining that the request body is too big.. I'm not sure why it would be. Below is my code:

```
<input type="file" @ref="inputTypeFileElement" />
<button type="button" @onclick=ReadFile>Read file</button>

@code {
    private ElementRef inputTypeFileElement;

    public async Task ReadFile()
    {
        foreach (var file in await fileReaderService.CreateReference(inputTypeFileElement).EnumerateFilesAsync())
        {
            var buffer = new byte[16384];
            int read = 0;
            using (Stream stream = await file.OpenReadAsync())
            {
                using (var fileStream = new FileStream("incomingFile.bin", FileMode.Create, FileAccess.Write))
                {
                    while ((read = await stream.ReadAsync(buffer, 0, buffer.Length)) > 0)
                    {
                        await fileStream.WriteAsync(buffer, 0, read);
                    }
                }
            }
        }
    }
}
```

**Comment by Tewr** [comment]
I think I agree on most points you've made, this is unexpected behavior. IIS is probably right though, so I'll have to try to reproduce this. The only thing I could think of that would provoke this (except for a blazor framework bug) would be websocket long polling transport but it's quite far-fetched.

In the meantime, you can probably work around this using "traditional" IIS configurations like `maxAllowedContentLength `or `MaxRequestBodySize`. Could you post your current `Startup.cs` as well for completeness?

**Comment by hamishfagg** [comment]
I've looked everywhere but Blazor doesn't seem to have a way to change those IIS setting. There's no web.config for example.

Startup.cs:
```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddSingleton<WeatherForecastService>();
            services.AddFileReaderService(options => options.InitializeOnFirstCall = true);
        }


        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });
        }
    }
```

**Comment by Tewr** [comment]
~~Try `webBuilder.UseHttpSys(o => o.MaxRequestBodySize = 50_000_000)` in `Program.cs` ?~~

Youre right looks like there is no corresponding setting for IIS in the inline config (`UseIIS `has no options)

**Comment by Tewr** [comment]
I can reproduce this under ~~preview9~~ preview8 as well and latest version of the lib (IIS express). However, I tried under IIS (rather than IIS Express) and by default, WebSockets are not enabled, so SignalR falls back to XHR. Its quite slow but the file transfers without problems.

Ill try to find the time in the coming days to configure IIS with websockets (then I'll have access to `maxAllowedContentLength` for sure). This smells like a framework bug.

**Comment by Tewr** [comment]
I tried using IIS/WebSockets with `maxAllowedContentLength` set to 100Mb but the problem remains. So much for my "for sure".

Kestrel however, works over WebSockets without problems. Simply by using 
`webBuilder.UseKestrel()`; in `Program.cs`

Possibly an issue with SignalR / IIS. It is as if the IIS security treats the WebSocket chit-chat like one long single message. I'll try to tinker a bit more with this but I probably need the help of the asp.net team.

**Comment by Tewr** [comment]
I have made a minimal repro of this problem and posted to asp.net issues at https://github.com/aspnet/AspNetCore/issues/13470

**Comment by Tewr** [comment]
here's a workaround I've found:

In `Startup.cs` Configure(), add

```
  app.Use(async (context, next) =>
            {
                context.Features.Get<IHttpMaxRequestBodySizeFeature>()
                    .MaxRequestBodySize = null;

                await next.Invoke();
            });

```
Not very nice though, as the limit is there for a reason.

**Comment by Tewr** [comment]
Framework bug confirmed. Apparently the fix will have to wait until 3.0 as p9 is too close.

30MB in _total throughout the life of a connection_ is enough to provoke it. And not only blazor but signalr under IIS in general affected. So five times a 5MB upload will also provoke this, or just any long-lived application that transfers enough data during the session.

Fortunately the workaround above should be quite ok for a blazor server-side app, as long as the server does not expose any endpoint other than signalR (signalR is _supposed_ to have this set to null, this is the regression)

**Comment by ADefWebserver** [comment]
> 30MB in _total throughout the life of a connection_ is enough to provoke it. 

Thanks for commenting on this. A few questions if I may...

1. So using your workaround prevents this until a fix?
2. Would this apply to an Azure Web App running under web sockets?

**Comment by Tewr** [comment]
1) yes, for blazor apps at least. I'll put it in the readme when I get my hands on a laptop

2) afaik Azure Web Apps are running IIS but I have not tested blazor nor SignalR on this platform so I don't know any details about sdk etc, you would have to try it out... The regression is there since preview6. If your web app is effectively using preview6-preview8 I'd say yes.

**Comment by hamishfagg** [comment]
Thanks for all of your work on this @Tewr, much appreciated.
I can confirm your workaround works for me, though it doesn't work if placed at the end of `Configure()`. I don't know what it needs to go before... Just stuck it at the top now.

Would you like to me to leave this open till the asp bug is fixed in case someone has the same issue? Or just close it?

**Comment by ADefWebserver** [comment]
@Tewr - It looks like they got the fix done for 3.0. You-are-a-God :)

**Comment by ADefWebserver** [comment]
> 2\. afaik Azure Web Apps are running IIS but I have not tested blazor nor SignalR on this platform so I don't know any details about sdk etc, you would have to try it out... The regression is there since preview6. If your web app is effectively using preview6-preview8 I'd say yes.

I am successfully running this upload component on Azure Web Apps with web sockets turned on. Average upload is only 1 meg so I haven't run into an issue so far. Anyway I will put in the fix.

**Comment by dharmaturtle** [comment]
Might be useful to add @IVData's code to the examples - downloading files is a common thing to do.
