### ISSUE TITLE
Usage IRL

### ISSUE THREAD

**Issue by EdCharbeneau** [Tewr/BlazorFileReader#8]
Hi, I wanted to leave an example of this library being used in a demo of a real world scenario.

I shared this on my Twitch TV Show: [Blazor StateHasChanged](https://twitch.tv/edcharbeneau)
https://youtu.be/-IuZQeZ10Uw

Code:
https://github.com/EdCharbeneau/BlazorStateCognitive/blob/master/BlazorStateCognitive.Client/Pages/FetchData.cshtml

**Comment by Tewr** [comment]
Nice, thanks. v0.7.0 of blazor broke most of my 'fun' demos due to optimizations in the build process. I guess uploading an image into dom could be a nice and simple thing to include in the demo project.

**Comment by EdCharbeneau** [comment]
Absolutely, it was quick validation to see if I was reading the file correctly and didn't corrupt the image in some way.
