### ISSUE TITLE
Fatal error in IL Linker - prev. 9

### ISSUE THREAD

**Issue by Zsolt-Bendes** [Tewr/BlazorFileReader#80]
Hi there.

I'm using this library to upload relatively small images on **client side Blazor**. After updating to prev 9 at compile time I get 
` Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Blazored.Typeahead.BlazoredTypeaheadBase`1/<HandleFocus>d__63::MoveNext()' in assembly: 'Blazored.Typeahead.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<!!0> Microsoft.JSInterop.IJSRuntime::InvokeAsync(System.String,System.Object[])` this error.
(In prev. 8 everything worked fine)
Please let me know if you have encountered something similar or know where to look for a solution. 
Thank you

The full error message:

Processing embedded resource linker descriptor: System.Text.Json.xml
  Processing embedded resource linker descriptor: System.Text.Encodings.Web.xml
  Processing embedded resource linker descriptor: mscorlib.xml
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.WasmRuntime (All).  Duplicate uses (All)
  Duplicate preserve in resource System.Text.Encodings.Web.xml in System.Text.Encodings.Web, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Text.Encodings.Web.TextEncoder (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource System.Text.Encodings.Web.xml in System.Text.Encodings.Web, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Buffers.OperationStatus System.Text.Encodings.Web.TextEncoder::EncodeUtf8Shim(System.Text.Encodings.Web.TextEncoder,System.ReadOnlySpan`1<System.Byte>,System.Span`1<System.Byte>,System.Int32&,System.Int32&,System.Boolean)
  Duplicate preserve in resource System.Text.Encodings.Web.xml in System.Text.Encodings.Web, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Int32 System.Text.Encodings.Web.TextEncoder::FindFirstCharacterToEncodeUtf8Shim(System.Text.Encodings.Web.TextEncoder,System.ReadOnlySpan`1<System.Byte>)
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Text.Json.JsonPropertyInfoNullable`2 (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Void System.Text.Json.JsonPropertyInfoNullable`2::.ctor()
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Text.Json.Serialization.JsonPropertyInfoNotNullableContravariant`4 (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Void System.Text.Json.Serialization.JsonPropertyInfoNotNullableContravariant`4::.ctor()
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Text.Json.Serialization.Converters.JsonConverterEnum`1 (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Void System.Text.Json.Serialization.Converters.JsonConverterEnum`1::.ctor(System.Text.Json.Serialization.Converters.EnumConverterOptions)
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Void System.Text.Json.Serialization.Converters.JsonConverterEnum`1::.ctor(System.Text.Json.Serialization.Converters.EnumConverterOptions,System.Text.Json.JsonNamingPolicy)
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Text.Json.Serialization.Converters.JsonKeyValuePairConverter`2 (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource System.Text.Json.xml in System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 of System.Void System.Text.Json.Serialization.Converters.JsonKeyValuePairConverter`2::.ctor()
  Type System.Reflection.Assembly has no fields to preserve
  Type Mono.ValueTuple has no fields to preserve
  Fatal error in IL Linker

  Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Blazored.Typeahead.BlazoredTypeaheadBase`1/<HandleFocus>d__63::MoveNext()' in assembly: 'Blazored.Typeahead.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<!!0> Microsoft.JSInterop.IJSRuntime::InvokeAsync(System.String,System.Object[])
     at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
     at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)

**Comment by ADefWebserver** [comment]
Perhaps this is related to [implementations of IJSRuntime to return ValueTask<T>](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/).

**Comment by Tewr** [comment]
I am compiling both with and without linker and I have had no problems at all at compile-time. The only issue I've had so far is visual studio has changed something, so I can't run my server-side e2e tests anymore and I probably will have to rewrite the wiring.

>Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void **Blazored.Typeahead**.BlazoredTypeaheadBase1/d__63::MoveNext()' in assembly: '**Blazored.Typeahead**.dll' -

Unless the [nuget page](https://www.nuget.org/packages/Blazored.Typeahead/) is wrong, this library is not upgraded to p9 yet. this is most likely your problem. remove it and see if things work better.

regards.

**Comment by Zsolt-Bendes** [comment]
@Tewr 
You are right. Blazored.Typeahead is still in prev 8. 
Sorry, this was my mistake. I wait for an update the lib. 

Thank you for the help and the quick answer!
