### ISSUE TITLE
How to read multiple files without drag-n-drop?

### ISSUE THREAD

**Issue by kaanlab** [Tewr/BlazorFileReader#84]
Try this code but FileReader see only last file
`
   <input type="file" multiple @ref=inputElement />
  <button @onclick="Add" class="btn btn-primary">read</button>
  <button @onclick="ReadFile" class="btn btn-primary">read</button>
  @code 
  {
     ElementReference inputElement;
    IFileReaderRef fileReaderReference;

    public async Task AddToList()
    { 
        fileReaderReference = fileReaderService.CreateReference(inputElement);
    }

    public async Task ReadFile()
    {
    ....
        foreach (var file in await fileReaderReference.EnumerateFilesAsync())
        {
            ....
         }
    }
  }
`

**Comment by Tewr** [comment]
Your code must be missing something. just to be sure, I just tried using the basic examples in the demo using the "multiple" attribute and it's working fine.

Provide an example of code that can be executed that reproduces the problem you are having and I might be able to help you out.

**Comment by kaanlab** [comment]
[This is my example](https://gist.github.com/kaanlab/9e97f154c9065f582f71364790f6ebb5)
At first step i append files to list and add description to each file, at the second step - read all files.

**Comment by kaanlab** [comment]
[This is my example for multiple file upload](https://gist.github.com/kaanlab/c729e146efc85f243609e1ef3ccec577)
but `List<IFormFile> files` in UploadController are empty.
But drag-and-drop example work fine with same action in UploadController

**Comment by Tewr** [comment]
When is `AddToList()` called? it is not referenced? I don't see how this could work at all, seeing you're not initializing the `fileReaderReference`. 

Use either [`await fileReaderService.CreateReference(inputElement).EnumerateFilesAsync()`](/Tewr/BlazorFileReader/blob/master/src/Demo/Blazor.FileReader.Demo.Common/IndexCommon.razor)
or initialize a reference to `fileReaderReference` in [`OnAfterRenderAsync(bool isFirstRender)`](https://github.com/Tewr/BlazorFileReader/blob/26bb03913d8fdf7c798dc0ab8601c7943df67788/src/Demo/Blazor.FileReader.Demo.Common/DragnDropCommon.razor#L54) like in the drag n drop example

**Comment by kaanlab** [comment]
Add `protected override void OnAfterRender(bool isFirstRender) ` but still not working: [updated example](https://gist.github.com/kaanlab/c729e146efc85f243609e1ef3ccec577)

**Comment by Tewr** [comment]
> Try this code but FileReader see only last file

> but List<IFormFile> files in UploadController are empty.

What is the problem exactly? do you get only one file or is the file list completely empty?

In any case, This line `multipartFormDataContent.Add(fileContent, "file", "fileName");` in a loop looks suspicious to me. I'm not sure what to put there but you probably should not put the same thing every time.

have a look at this example: https://stackoverflow.com/questions/16906711/httpclient-how-to-upload-multiple-files-at-once/16908077#16908077 

Also on a side note, that answer is using `StreamContent(stream)`  instead of `MemoryStream` wrapped in `ByteArrayContent`, which is an approach I'd recommend (`MemoryStream` in `ByteArrayContent` will scale very badly unless properly protected)

Recommended method:
```
var bufferSize= 8192; // You can experiment with this, but keep it < 24000
var myStream = await file.OpenReadAsync();
var content = new StreamContent(myStream, bufferSize);
```

**Comment by kaanlab** [comment]
> What is the problem exactly? do you get only one file or is the file list completely empty?

Yes, list is empty, but in drag-n-drop example list is filled with data.

> In any case, This line multipartFormDataContent.Add(fileContent, "file", "fileName"); in a loop looks suspicious to me. I'm not sure what to put there but you probably should not put the same thing every time.

I wanted to write a simpler code. Instead "fileName" i use
 `fileInfo = await file.ReadFileInfoAsync(); 
fileInfo.Name;`

Thank you for stream enhancement.

**Comment by Tewr** [comment]
Are you using server-side or client-side blazor?

**Comment by kaanlab** [comment]
Client-side, preview9

**Comment by Tewr** [comment]
here is full working minimal code, i just debugged it, I see no problem. Now I'm a bit disappointed, which is weird, cause its nice that is working. 

Now at least, just copy my code, build from there and you will be fine. Don't know what you missed but it's not a problem with the library. I should keep this somewhere...

uploadmvc.razor

```
@page "/UploadMvc"
@inject IFileReaderService fileReaderService
@inject HttpClient HttpClient

<h3>Upload multiple</h3>
<input type="file" multiple @ref=inputElement />
<button @onclick="UploadFiles">Upload</button>
<br /><pre>@debug</pre>
@code {
    string debug;
    ElementReference inputElement;
    IFileReaderRef fileReaderReference;

    protected override void OnAfterRender(bool isFirstRender)
    {
        fileReaderReference = fileReaderService.CreateReference(inputElement);
    }

    public async Task UploadFiles()
    {
        var multipartFormDataContent = new MultipartFormDataContent();
        foreach (var file in await fileReaderReference.EnumerateFilesAsync())
        {
            multipartFormDataContent.Add(
                new StreamContent(await file.OpenReadAsync(), 8192),
                "files",
                (await file.ReadFileInfoAsync()).Name);
        }

        var res = await HttpClient.PostAsync(requestUri: "/api/upload/files", content: multipartFormDataContent);
        debug = await res.Content.ReadAsStringAsync();
    }
}
```

uploadcontroller.cs
```
        [HttpPost("files"), DisableRequestSizeLimit]
        public async Task<IActionResult> UploadFiles(List<IFormFile> files)
        {
            var result = files.Select(file => new { Name = file.FileName, Length = file.Length }).ToList(); ;
            return Ok(result);
        }
```

**Comment by kaanlab** [comment]
Thank you!
