### ISSUE TITLE
Save to IFileReference

### ISSUE THREAD

**Issue by kaanlab** [Tewr/BlazorFileReader#85]
Can i write data directly to IFileReference? I want to resize image in browser, save data and then send data to API controller.
Something like this:
<code>
using (var stream = await file.CreateMemoryStreamAsync())
{
            using (Image image = Image.Load(stream))
            {
                image.Mutate(x => x.Resize(image));
                image.SaveAsJpeg(stream);
            }
       // save back to IFileReference
       await stream.WriteAsync(file);
}
</code>
I use client-blazor RC1

**Comment by Tewr** [comment]
No, this library exposes a read-only stream. You need to write modifications to another stream.

I don't know what Image class you are using here in your example, but if you refer to the `System.Drawing` Image class you probably won't have much luck as they depend on GDI, which is platform-specific (native) and probably not implemented on the `mono-wasm` platform.

That said, it may be possible with ImageSharp, but I haven't tried it.

**Comment by kaanlab** [comment]
Ok, thank you
