### ISSUE TITLE
Regression?

### ISSUE THREAD

**Issue by PhilPJL** [Tewr/BlazorFileReader#88]
Updating to latest version

![image](https://user-images.githubusercontent.com/271656/65269870-eede8c00-db11-11e9-9ad2-34f96a822c26.png)

The error message is back

![image](https://user-images.githubusercontent.com/271656/65269937-0c135a80-db12-11e9-873f-2d86fd00bac7.png)

![image](https://user-images.githubusercontent.com/271656/65270040-441a9d80-db12-11e9-8434-ca15ab54a5e0.png)

**Comment by Tewr** [comment]
Thank you for the report. Yes. I missed the parameter in the pack command. I gotta put up a CI for this step so I won't forget.. This is fixed in 0.16.0.19262.
