### ISSUE TITLE
Implement CopyToAsnyc(stream, bufferSize) in js interop

### ISSUE THREAD

**Issue by rpskelton2** [Tewr/BlazorFileReader#93]
If you were to implement CopyToAsnyc(stream, bufferSize) in the js interop it would vastly simplify consuming code that wants to pull down the stream in chunks to stay under the SignalR buffer limit.

**Comment by Tewr** [comment]
Hello! Thank you for your feedback! But I'm not sure I'm following here. Could you back up a bit, a bit more context? Is something stopping you from using `CopyToAsync` as it is today?

**Comment by rpskelton2** [comment]
Hello, I'm not a streaming expert so apologies in advance if I'm missing something.

I attempted to use code like below on a server side blazor application.  When run, it appears to be hanging in the js interop and finally the CopyToAsync task will timeout/cancel.  When I briefly looked at your code I didn't see an override implementation of CopyToAsync in FileReaderJsInterop.InteropFileStream.cs so I assumed(*) that was the issue.

 using (var ms = new MemoryStream())
                {
                    using (var fs = await file.OpenReadAsync())
                    {
                        await fs.CopyToAsync(ms, BufferSize);
                    }
   ...


I am able to accomplish the same thing by using Buffer.BlockCopy in a loop to copy bytes to an array so it's not a huge deal.  Thanks!

                using (var fs = await file.OpenReadAsync())
                {
                    while ((count = await fs.ReadAsync(buffer, 0, buffer.Length)) != 0)
                    {
                        Buffer.BlockCopy(buffer, 0, imageBytes, index, count);
                        index += count;
                    }
                }

**Comment by Tewr** [comment]
The default implementation of `Stream.CopyToAsync` in the base class calls `ReadAsync`repeatedly with the specified BufferSize if `ReadAsync` is overridden, so no need for me to override `Stream.CopyToAsync`.

The following is working code, I just tried it in SSB:

```
using (var fs = await file.OpenReadAsync())
using(var target = File.OpenWrite(@"c:\temp\test.bin"))
{   
  await fs.CopyToAsync(target, BufferSize);
  await target.FlushAsync();
}
```

**Comment by rpskelton2** [comment]
I just did some more testing and I'm hitting the signalr buffer limit using fs.CopyToAsync(target, BufferSize).  My hope had been that if BufferSize was smaller than the signalr buffer that CopyToAsync would still chunk it in BufferSize pieces  (my BufferSize is 70% of signalr).  I probably just misunderstood how CopyToAsync works.

In any case if I use Buffer.BlockCopy as in the code above it will take as large a file as I can give it event with the default 32k signalr buffer.

Thanks for putting this package together!

**Comment by Tewr** [comment]
OK, thanks for the info. I think what you're saying makes sense though, I dont see any misunderstanding.

Here is the source code for [CopyToAsync](https://referencesource.microsoft.com/#mscorlib/system/io/stream.cs), theres really nothing special in there:

 ```
 private async Task CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
        {
            Contract.Requires(destination != null);
            Contract.Requires(bufferSize > 0);
            Contract.Requires(CanRead);
            Contract.Requires(destination.CanWrite);
 
            byte[] buffer = new byte[bufferSize];
            int bytesRead;
            while ((bytesRead = await ReadAsync(buffer, 0, buffer.Length, cancellationToken).ConfigureAwait(false)) != 0)
            {
                await destination.WriteAsync(buffer, 0, bytesRead, cancellationToken).ConfigureAwait(false);
            }
        }
```

However, I agree that the SignalR size limit is inconvenient. Multithreading has been proposed by Steve Sanderson to work around it, using an intermediate large buffer. Other than being more convenient, it also maximizes throughput.

**Comment by Tewr** [comment]
I'm closing this as I think we've sorted out most stuff even if there is some doubts on the source of the initial problem, I'll reopen if you disagree.
