### ISSUE TITLE
Limit size of file upload

### ISSUE THREAD

**Issue by nguyenvanbien95** [Tewr/BlazorFileReader#94]
How to set limit size of upload file using IFileReaderService?

**Comment by Tewr** [comment]
Hello.

Take a look at the `IFileInfo.Size` property before starting the consumption of the stream, and compare to your upper limit.

The [demo](https://github.com/Tewr/BlazorFileReader/blob/081516a2de46fb65b410632991f59305291f21e3/src/Demo/Blazor.FileReader.Demo.Common/IndexCommon.razor#L48) shows an example of how to read this property.
