### ISSUE TITLE
Blazor 3.1 Preview 4 / ASP.NET Core 3.1 compatibility issue

### ISSUE THREAD

**Issue by vfrz** [Tewr/BlazorFileReader#95]
The library stopped working since I updated my application to latest blazor version (3.1 preview 4 aka ASP.NET Core 3.1 release).
The javascript file "FileReaderComponent.js" is not loaded in the page automatically anymore.
This is maybe related to this: https://github.com/aspnet/AspNetCore/issues/13103

For now my workaround is to copy the js file to my own project and include it in index.html

**Comment by Tewr** [comment]
Thank you for the report and the workaround. I'll have to read up on how this works in 3.1 p4 .

**Comment by IvanJosipovic** [comment]
It appears that static resources are no longer loaded automatically in Blazor CSB. They need to be loaded manually like Blazor SSB.

**Comment by Tewr** [comment]
@vfrz can you try using `options.InitializeOnFirstCall = true`
In addition to `options.UseWasmSharedBuffer = true` in the setup? That should work as well.

**Comment by Tewr** [comment]
Also, a third workaround would be to call `await IFileReaderService.EnsureInitializedAsync()`. This is slightly less expensive than  `options.InitializeOnFirstCall` as it only has to be called once, the drawback being that you need to put it in some nifty event that's only being called once per session, or wrap it's with a static boolean to make sure you don't call it twice, as it's redundant.

**Comment by Tewr** [comment]
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1/:

> Support for static assets in libraries when publishing
> Standalone Blazor WebAssembly apps now support static assets from Razor class libraries both during development and when publishing. This applies to both standalone Blazor WebAssembly apps and ASP.NET Core hosted apps. Static assets are consumed from referenced libraries using the path prefix: _content/{LIBRARY NAME}/.

So looks like static assets have to be included explicitly in wasm projects. Shouldn't have to copy the file though, should just be _content/Tewr.Blazor.FileReader/FileReaderComponent.js

Question is, do I have to republish my package for this to work?

**Comment by vfrz** [comment]
I've tried to import the js file using `_content/Tewr.Blazor.FileReader/FileReaderComponent.js` path, but it's not working. Actually I don't know if republishing the package is required.

Btw setting InitializeOnFirstCall to true makes it work.

Thanks for your help.

**Comment by IvanJosipovic** [comment]
Try removing the "latest", this broke static resource publishing for me.
https://github.com/Tewr/BlazorFileReader/blob/081516a2de46fb65b410632991f59305291f21e3/src/Blazor.FileReader/Blazor.FileReader.csproj#L7

**Comment by Tewr** [comment]
@IvanJosipovic thanks ill have a look.

 I really dislike complicated setups, so I'm leaning against setting `InitializeOnFirstCall` to `true` as a default setting even if the langversion thing might be relevant. I'll have to do some testing.

**Comment by Tewr** [comment]
A

**Comment by pablopioli** [comment]
Importing the file FileReaderComponent.js worked for me.

I **guess** republishing is not required. As Blazor Wasm is in beta, workarounds are expected. Who knows if another breaking change is in the next preview?
