### ISSUE TITLE
Moving of unreaded bytes in stream

### ISSUE THREAD

**Issue by bermanUnicorn** [Tewr/BlazorFileReader#98]
Hi, thanks for your project! It was very helpful for me in my serverside Blazor app.
My case assume that uploading files can be much larger than i wanna scale my SignalR message size :)

I found some behavior, that, I think, is a bug or smth:
When you try to read stream content part by part such as default workflow with FileStream - you will override begining of your buffer. As i noticed - it happens because stream data moving to the begining after each reading step.

I have prepared very simple example that can show this issue:
https://github.com/bermanUnicorn/BlazorFileReader_StreamIssue

**Comment by Tewr** [comment]
Hello! Using a single huge buffer rather than a buffer representing a single transfer is indeed a very rare use case. I didn't try it, and when reading the code I think you are most likely right, this is currently not working. The target buffer must represent a chunk and nothing else.

**Comment by Tewr** [comment]
@bermanUnicorn in the mean time, you can use any of the examples in the project, they all work regardless of file size, as long as your `offset = 0` and `count = buffer.length`.
